### ISSUE TITLE
unable to launch when running in Ubuntu Unity

### ISSUE THREAD

**Issue by Xtigyro** [shiftkey/desktop#150] opened 2019-05-20 05:51 UTC
Using Ubuntu 19.04 and Unity 7.5.0+19.04.20190304-0ubuntu1.
GitHub Desktop cannot start. The errors:
[running-github_desktop.log](https://github.com/shiftkey/desktop/files/3201045/running-github_desktop.log)

**Comment by shiftkey** [comment] 2019-05-20 12:09
@Xtigyro thanks for the report! I'm curious if you're able to find what is triggering this segmentation fault (maybe running it under `strace` will show the underlying error?)

```
Segmentation fault (core dumped)
```

**Comment by Xtigyro** [comment] 2019-05-21 06:07
Hey @shiftkey - these are the logs from `strace`!
[strace-github_desktop-without-sudo.log](https://github.com/shiftkey/desktop/files/3201035/strace-github_desktop-without-sudo.log)

And running it with `sudo`:
[strace-github_desktop-with-sudo.log](https://github.com/shiftkey/desktop/files/3201032/strace-github_desktop-with-sudo.log)

**Comment by Xtigyro** [comment] 2019-05-21 06:21
And running it with `sudo`:
[strace-github_desktop-with-sudo.log](https://github.com/shiftkey/desktop/files/3201032/strace-github_desktop-with-sudo.log)

**Comment by shiftkey** [comment] 2019-05-21 12:54
@Xtigyro thanks for the logs. This looks like the same issue as we're tracking in #142. 

Can you confirm what steps you were performing with the app before it would crash?

```
close(21)                               = 0
openat(AT_FDCWD, "/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/tls/haswell/x86_64/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/tls/haswell/x86_64", 0x7ffd730993c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/tls/haswell/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/tls/haswell", 0x7ffd730993c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/tls/x86_64/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/tls/x86_64", 0x7ffd730993c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/tls/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/tls", 0x7ffd730993c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/haswell/x86_64/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/haswell/x86_64", 0x7ffd730993c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/haswell/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/haswell", 0x7ffd730993c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/x86_64/libpng12.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
stat("/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/x86_64", 0x7ffd730993c0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/snap/github-desktop/59/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/../../../../../../lib/x86_64-linux-gnu/libpng12.so.0", O_RDONLY|O_CLOEXEC) = 21
```

**Comment by Xtigyro** [comment] 2019-05-21 19:17
@shiftkey Hey - the app cannot start. The logs represent the start sequence of the app which ends with a segmentation fault. No app window is visualized, etc.

If I switch to GNOME on the same system - the app starts and works fine.

**Comment by bogdan-marian** [comment] 2019-06-05 21:23
Same for me: Ubuntu 19.04 and snap version
Steps to reproduce. 

```
snap remove github-desktop
snap install github-desktop --beta --classic
github-desktop
# skip: "welcome to GitHub Desktop"
# Continue: "Configure Git"
# Yes: Make GitHub Desktop better!
#  Add an Existing Repository from your hard drive...
# Local path Choose.. : And this is where you get the crash
Segmentation fault (core dumped)
```

Te (core dumped) message appears write after clicking the "Choose" button. 

[bogdan-snap.log](https://github.com/shiftkey/desktop/files/3259110/bogdan-snap.log)

**Comment by shiftkey** [comment] 2019-06-05 21:40
@bogdan-marian I think you'd be interested in #142 which feels like it's a similar root cause here

**Comment by irven-cy** [comment] 2019-06-13 22:20
@shiftkey 
Keep going :star: I'm happy to be the 800th star :smiley:

**Comment by shiftkey** [comment] 2020-03-29 18:42
I'm not familiar enough with Ubuntu Unity to be able to troubleshoot this at all, as well as know how to support Electron apps there, and a lot has changed since then (including Ubuntu focusing on GNOME from 18.04 onwards) so I'm going to close this out because I don't plan to spend any more time here.

**Closed as completed by shiftkey** 2020-03-29 18:42 UTC
Labels: unclear, bug
