### ISSUE TITLE
Basic actions take long time

### ISSUE THREAD

**Issue by Meetem** [shiftkey/desktop#365] opened 2020-11-01 12:59 UTC
### Describe the bug
Basic actions like commit/discard/push takes noticeable longer than on windows (sometimes about 10x times).
But there's solution -- resize UI. 

### Version & OS
Version 2.5.4-linux1
Ubuntu 20.04.1 LTS
Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux 

### Steps to reproduce the behavior
1. Commit/discard any tiny change (this shouldn't take longer than 1-2 seconds)
1. Wait long time.
2. Start nervously make useless actions like resizing GitHub Desktop's UI 
3. Enjoy process completion.

### Screenshots
It's better to see on video: https://youtu.be/cEj5TAmOaco

-- May be it's linked with https://github.com/shiftkey/desktop/issues/332

**Comment by shiftkey** [comment] 2020-11-01 22:20
@Meetem I believe this is the same root cause as #329 and #332 and I wrote some notes on where I think the problem lies here https://github.com/shiftkey/desktop/issues/329#issuecomment-683434326

Unless you have a different repro to those two, I'd like to close this issue to prevent things from getting noisy. Let me know if you're okay with that.

**Comment by shiftkey** [comment] 2020-11-06 01:47
Closing this out as we have #329 and #332 that cover this issue

**Closed as completed by shiftkey** 2020-11-06 01:47 UTC

**Comment by Jick-study** [comment] 2020-11-22 10:28
@shiftkey @Meetem 
目前最新版本依旧选择文件回滚时会卡顿。即使我只是修改了很少的代码，选择回滚依旧会卡顿很久，这个问题可以修复吗？
建议与2.5.3版本对比，这个版本选择回滚时，即使同时回滚几十个文件也就2秒。
