### ISSUE TITLE
.deb package name shouldn't be `desktop`

### ISSUE THREAD

**Issue by tilda** [shiftkey/desktop#37] opened 2018-04-04 22:53 UTC
I noticed while installing the .deb on my computer, that the package name in the .deb file was `desktop`.

You should probably rename the package to something like `github-desktop`.

**Comment by shiftkey** [comment] 2018-04-04 23:54
@tilda thanks for the report. I'm pretty sure this is a duplicate of #22, so please follow along with that issue.

**Closed by shiftkey** 2018-04-04 23:54 UTC

**Comment by tilda** [comment] 2018-04-04 23:59
Alright, thanks!
