### ISSUE TITLE
Fedora LibCurl

### ISSUE THREAD

**Issue by Aeirex** [shiftkey/desktop#40] opened 2018-04-19 02:21 UTC
Fedora is broken when you pull, commit, or sync.
libcurl-gnutls.so.4

I read that you have to create a symbolic link since Fedora uses a different name.
ln -s libcurl.so.4.4.0 libcurl-gnutls.so.4
Although, this is old and won't work on the latest release of Fedora.

![screenshot from 2018-04-18 21-21-21](https://user-images.githubusercontent.com/1341321/38967826-74daf684-434e-11e8-9401-be5427c4a5c5.png)

**Comment by probonopd** [comment] 2018-04-19 05:01
Maybe bundle a private libcurl.

Reference:
https://github.com/AppImage/AppImages/issues/187

**Comment by shiftkey** [comment] 2018-04-19 13:37
Closing as a duplicate of #21. There is also a discussed [workaround](https://github.com/shiftkey/desktop/issues/21#issuecomment-357715905) in there.

**Closed by shiftkey** 2018-04-19 13:37 UTC
