### ISSUE TITLE
Discard changes doesn't work with encrypted home directory

### ISSUE THREAD

**Issue by mlerota** [shiftkey/desktop#124] opened 2019-02-20 16:02 UTC
How to reproduce: Right click on the change, and click "Discard changes" or "Discard all changes" and it doesn't happen. In the logs I can only see "info: [ui] No submodules found. Skipping "git submodule status"". 

Tried mac os x version and it works there.

**Comment by shiftkey** [comment] 2019-02-20 18:31
@mlerota what happens if you open **View** | **Toggle Developer Tools** and check the console - any other context there?

**Comment by mlerota** [comment] 2019-02-20 20:17
No, only that message:
No submodules found. Skipping "git submodule status". 

Does it work on your version of Linux?

**Comment by immackay** [comment] 2019-04-26 06:24
Would you be able to reproduce the issue and provide the log file?

**Comment by shiftkey** [comment] 2019-04-26 14:39
@immackay my best guess is that it's similar or the same as #91, as some Git calls rely on being able to access `/usr/bin/gettext.sh` which is available in [`gettext`](https://www.archlinux.org/packages/core/x86_64/gettext/).

**Comment by immackay** [comment] 2019-04-28 02:58
I'm unsure if adding the `nss` and `nspr` dependencies fixed this, but I'm unable to reproduce this issue on the fresh VM I just spun up.

Though I agree that missing `gettext` would likely be an issue, it is part of both the `base` and `base-devel` groups, and as such it should be installed on most if not all Arch installations. I will add it as a dependency for the next update.


EDIT: the behaviour listed above did exist the first time I ran github-desktop, but after relaunching (perhaps after creating `~/.local/share/Trash`?) the issue did not persist.

**Comment by shiftkey** [comment] 2019-05-12 15:52
> EDIT: the behaviour listed above did exist the first time I ran github-desktop, but after relaunching (perhaps after creating ~/.local/share/Trash?) the issue did not persist.

This might explain it, but I'm not sure how aggressive I should be with this. @mlerota was this something you've been able to reproduce?

**Comment by mlerota** [comment] 2019-05-12 19:07
Just created a new user and tried to reproduce the error. With new user, everything works fine. So I tried to delete my config ~/.config/GitHub\ Desktop. But with my user, the problem persist. Is there any other config dir or file that Github Desktop use?

**Comment by shiftkey** [comment] 2020-03-29 13:31
@mlerota apologies for the delay in following up here:

>  Is there any other config dir or file that Github Desktop use?

I'm not aware of any other directories here that might be important to "Discard Changes" but it's been a while since I've looked at this area. If the Git operation works fine (so no `gettext` issue) it may be some Chromium dependency that's being used to move the items to "trash" and there's a lot of environment-specific code that could be involved:

https://github.com/electron/electron/blob/76ae3b7ecbd0eef93b6842319c791cc00cf9ef59/shell/common/platform_util_linux.cc#L107-L137

I noticed they've introduced a new environment variable [`ELECTRON_TRASH`](https://www.electronjs.org/docs/api/environment-variables#electron_trash-linux) that should work with the latest version of Desktop (`2.4.0` as of writing).

<img width="456" src="https://user-images.githubusercontent.com/359239/77850358-5acc3c00-71a8-11ea-8d3e-329468b7f178.png">

I'm not sure when this will be available on Archlinux but if you have know which option works for you I'd recommend setting the environment variable to see if it changes the behaviour of the app.

**Comment by mlerota** [comment] 2020-04-15 11:32
Hi @shiftkey. Sorry for the late reply. I waited for the new 2.4.0 version to come so maybe the problem would resolve itself. It was not the case. :-) But I finally found what is the problem. Encrypted homedir. I have one Private directory that is encrypted with eCryptfs. https://wiki.archlinux.org/index.php/ECryptfs In there I keep all the private stuff like passwords, credentials, ~/.ssh, etc.... Basically half of the home directory. So if someone steals my laptop, he/she will not be able to get this sensitive data. If my local git repositories are inside this private dir, this bug appears. If I move them out of there, everything works OK. So I guess it's something with this directory and encryption. Dir has this permission set: 
drwx------ 88 user user. Thanks.

**Comment by shiftkey** [comment] 2020-04-16 22:01
@mlerota thanks for the extra details. If you're able to put together a decent set of steps to reproduce the problem it'd be greatly appreciated to figure out the next steps, but for now I've updated the description to indicate what the root cause appears to be.

**Comment by shiftkey** [comment] 2023-12-18 21:33
> Encrypted homedir.

Closing this out as I don't have the bandwidth to dig into this case further, and the presence of an encrypted home directory combined with the usage of the `moveItemToTrash` provided by Electron suggests that this is probably something that needs to be handled by the upstream project - they may have additional users or expertise on this area to add to this discussion...

**Closed as not planned by shiftkey** 2023-12-18 21:33 UTC
Labels: unclear, bug
