### ISSUE TITLE
no valid openPgp data found

### ISSUE THREAD

**Issue by maramzan** [shiftkey/desktop#336] opened 2020-09-06 05:26 UTC
### Operating System/Distribution

Ubantu

### Installer

Which version of the app?
Which installer type?

### What happened?

when I run the command below to install github desktop
$ wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -

I am getting this issue
gpg: no valid OpenPGP data found.

**Comment by sgornick** [comment] 2020-09-07 04:58
This is a duplicate of issue #310

**Comment by shiftkey** [comment] 2020-09-07 21:21
Echoing #310:

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle should reset around the 22nd of the month. In the meantime the installers are available with each release on the [Releases](https://github.com/shiftkey/desktop/releases) page.

**Closed as completed by shiftkey** 2020-09-07 21:21 UTC
