### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by jsj19990602** [shiftkey/desktop#964] opened 2023-11-28 11:37 UTC
### The problem

if i click the github desktop and after a few minutes, it's screen become white

### Release version

3.3.5 and 3.3.4

### Operating system

ubuntu 20.04

**Comment by shiftkey** [comment] 2023-11-28 12:22
Duplicate of https://github.com/shiftkey/desktop/issues/958, please re-test with the latest release https://github.com/shiftkey/desktop/releases/tag/release-3.3.5-linux2 (has to be installed manually for now) and see if it resolves for your setup.

**Closed as not planned by shiftkey** 2023-11-28 12:22 UTC
