### ISSUE TITLE
Linux Mint 18.3, "10 second" issue 

### ISSUE THREAD

**Issue by hayridurmaz** [shiftkey/desktop#120] opened 2019-01-26 07:29 UTC
After installing [GitHubDesktop-linux-1.6.0-linux1.deb](https://github.com/shiftkey/desktop/releases/download/release-1.6.0-linux1/GitHubDesktop-linux-1.6.0-linux1.deb) on my Linux Mint 18.3 machine, I got an error saying `your session lasted only 10 seconds...` while trying to login

When click details:
`/etc/mdm/Xsession: Beginning session setup....`
(I unfortunately don't remember rest of the error)

I wasn't able to login. 

It was saying something like `bad variable name`  According to my search about the error, It is caused by PATH variable mistakes. Sorry for not giving very specific details, but I instantly deleted the github-desktop, since it was the last thing that might change my PATH variable, then error was gone.

**Comment by shiftkey** [comment] 2019-05-12 14:51
I'm going to close this out because I don't have the bandwidth currently to investigate what this might have been - apologies @hayridurmaz! If anyone else is able to reproduce this issue please open a fresh issue and fill out the provided **Bug report** template.

**Closed as completed by shiftkey** 2019-05-12 14:51 UTC
Labels: unclear
