### ISSUE TITLE
"Show in your File Manager" doesn't work in AppImage release, if using specific dotfiles

### ISSUE THREAD

**Issue by Rudxain** [shiftkey/desktop#870] opened 2023-04-19 05:37 UTC
### The problem

When clicking that button (in the context of a repo), it does nothing.

`xdg-open` cmd works properly, so it shouldn't be a mis-configured XDG settings

### Release version

3.2.0

### Operating system

Linux Mint 21.1 Cinnamon

### Steps to reproduce the behavior

0. Download the GHD AppImage & open it
1. Clone a repo
2. (Optional) Click the upper-most button labeled "Repository"
3. Click the button labeled "Show in your File Manager"
4. (nothing happens)

### Log files

That button (Show logs in your File Manager) also doesn't work

### Additional context

I suspect [my `$HOME` dotfiles](https://github.com/Rudxain/dotfiles) might be causing an issue

**Comment by Rudxain** [comment] 2023-04-19 05:42
Now, I tested on a "clean" user, and the "Show logs" button works!

It very likely means there's something wrong in my dotfiles

**Comment by Rudxain** [comment] 2023-07-18 03:02
It's not just my dotfiles, it's the upstream [/mathiasbynens/dotfiles](/mathiasbynens/dotfiles)

**Comment by shiftkey** [comment] 2023-11-27 00:28
Closing this out as something that I don't have bandwidth to resolve, but it's good to know that we know the root cause at least

**Closed as not planned by shiftkey** 2023-11-27 00:28 UTC
Labels: upstream-dependencies
