### ISSUE TITLE
Provide Flatpak builds

### ISSUE THREAD

**Issue by cassidyjames** [shiftkey/desktop#265] opened 2020-04-20 19:56 UTC
### Describe the feature or problem you’d like to solve

Users of elementary OS and other desktops may have a hard time finding, installing, and trusting this fork of the GitHub Desktop app.

### Proposed solution

If Flatpak builds were included, it would be a one-click install on elementary OS and many other Linux distros. Further, if the pipeline were set up with Flathub.org, it would be available in app stores out of the box on some distros and more discoverable on others.

### Additional context

Flatpak is just a packaging technology, not a store. You can provide Flatpaks in several ways, with different advantages. The simplest way in CI may be by building a Flatpak bundle, but I don't think that will handle updates. A better long-term solution would likely be to submit the Flatpak to a centralized remote like Flathub.

Flathub supports trusted developers pushing releases to Flathub via CI, though I'm not sure of the specifics. Hopefully someone from the project could chime in here.

I'm coming here [from Twitter](https://twitter.com/shiftkey/status/1252321841546493956). 😉

**Comment by shiftkey** [comment] 2020-04-20 20:08
:wave: thanks for starting this discussion off @cassidyjames!

The first thing that comes to mind is https://github.com/endlessm/electron-installer-flatpak which supports a programmatic API to generate the flatpak from a packaged Electron app using Node (which is how our other packaging works currently).

That's the path I'd like to try first for a couple of reasons:

 - it supports passing in options to configure the equivalent of a flatpak manifest, and appears to provide some sane defaults
 - it feels very similar to `electron-installer-debian`, which I've been using in #263 and felt less magical than `electron-builder`
 - it can follow our existing pattern for generating installers as part of a release

Once I've wrapped #263 I'll drop some instructions in here for how we can follow the same pattern from #263 if someone wants to take a shot at wiring up the packaging step.

**Comment by shiftkey** [comment] 2020-04-20 20:09
cc @jfgordon2 who I know contributed some Elementary OS integrations previously

**Comment by jfgordon2** [comment] 2020-04-20 20:36
@shiftkey this sounds super interesting, I'd be happy to take a look once you've established a pattern for the debian builder

**Comment by shiftkey** [comment] 2020-04-26 14:04
@jfgordon2 I merged #263 and was planning to publish an update during the week, but the key parts to the module can be found in [`script/package-debian.ts`](https://github.com/shiftkey/desktop/blob/90e4805cbeb2acc19b266abea91adfa038c35bff/script/package-debian.ts) if you wanted to setup an equivalent for flatpak support.

I also annotated the PR itself with additional context: https://github.com/shiftkey/desktop/pull/263#pullrequestreview-399235823

**Comment by gasinvein** [comment] 2020-05-10 17:48
Hello there. I've managed to build the app with flatpak-builder without network access, so it could be submitted to Flathub (offline builds are mandatory there).  
flatpak-builder manifest is [here](https://github.com/gasinvein/flatpak-apps-staging/tree/com.github.shiftkey.GitHubDesktop/master), sources are generated with flatpak/flatpak-builder-tools#118.

There are two major obstacles severely complicating build, and since I'm not very familiar with electron and friends, it would be nice if the developers could provide some help with these:
- There is no easy way to point electron-download to a pre-downloaded cache. I believe electron-get handles it better (at least it should respect `electron_config_cache` env var).
- node-sass must match `node` abi version (since it's used during build time), while other native modules must match electron's abi version. The tricky part is that since we build offline, node headers can't be downloaded on demand, only pointed to via `npm_config_nodedir` env var.

**Comment by shiftkey** [comment] 2020-05-10 21:29
> Hello there. I've managed to build the app with flatpak-builder without network access, so it could be submitted to Flathub (offline builds are mandatory there).

@gasinvein I'd love to hear more about this, especially the offline builds bit, because this feels like a fair bit of additional work to adapt things. Not to say it's impossible, it's just going against how the project tooling has been optimized.

**Comment by gasinvein** [comment] 2020-05-10 22:04
@shiftkey By default, flatpak-builder downloads all sources by itself and runs build process without network access. While it's just a default for flatpak-builder, Flathub. the de-facto "flatpak store", require it. 
For things like yarn, there are some helpers that read `yarn.lock` and produce drop-in manifest part for flatpak-builder, which then populates yarn offline mirror before spawning build process. It's simple in general, but become trickier with node packages that do download files during install. Making such packages work usually involves pre-downloading download cache for them.

Also, keep in mind that it's only Flathub requirement, so if you don't plan to submit the app there - building offline isn't necessary.

**Comment by shiftkey** [comment] 2020-05-10 22:39
@gasinvein thanks for digging into this. I can fill in some context from my end about how things are setup.

> There are two major obstacles severely complicating build, and since I'm not very familiar with electron and friends, it would be nice if the developers could provide some help with these:

For context, the project itself contains two `package.json` files:

 - the one at the root is there for tooling, and any native modules would target the installed node version
 - the one under `app` is for the Electron-specific dependencies, and leverages the `app/.npmrc` config to target our specific version of Electron

> * There is no easy way to point electron-download to a pre-downloaded cache. I believe electron-get handles it better (at least it should respect `electron_config_cache` env var).

I believe `electron-download` is only used by `electron-chromedriver` these days, but `electron-download` does support an environment variable override to control where it downloads the files from: https://www.npmjs.com/package/electron-download

>> You can set the `ELECTRON_MIRROR` or `NPM_CONFIG_ELECTRON_MIRROR` environment variable or mirror opt variable to use a custom base URL for grabbing Electron zips.

> * node-sass must match `node` abi version (since it's used during build time), while other native modules must match electron's abi version. The tricky part is that since we build offline, node headers can't be downloaded on demand, only pointed to via `npm_config_nodedir` env var.

Ideally our Electron-specific native modules should use `prebuild` to obtain the native modules they need (based on the ABI version) from GitHub releases, so they shouldn't need to fall back to downloading headers and building from source.

It's been a while since I've checked those though - if you're seeing specific problem packages that don't seem to behave this way we can look into whether there are upgrades pending. Alternatively, if there's a cheat sheet of tools to install and commands to run against your repository to see these problems myself, I can dig into them later this week when I have some more time.

**Comment by gasinvein** [comment] 2020-05-10 23:05
> I believe `electron-download` is only used by `electron-chromedriver` these days, but `electron-download` does support an environment variable override to control where it downloads the files from: https://www.npmjs.com/package/electron-download

If I understood it right, electron-packager 13.x.x, used by GitHub Desktop, uses electron-download.

> > > You can set the `ELECTRON_MIRROR` or `NPM_CONFIG_ELECTRON_MIRROR` environment variable or mirror opt variable to use a custom base URL for grabbing Electron zips.

That's the problem - we can control only from where it'll _download_ electron, no way to make it use existing local files without downloading anything.

> commands to run against your repository to see these problems myself

I've already circumvent these problems, so the app can be built and ran like any other flatpak. It's just that applied workarounds are ugly and fragile, so it'll be hard to maintain.  
I guess that completely replacing electron-download with electron-get could help.

**Comment by shiftkey** [comment] 2020-05-10 23:54
> If I understood it right, electron-packager 13.x.x, used by GitHub Desktop, uses electron-download.

Looks like this got ported in [`v14.0.0`](https://github.com/electron/electron-packager/releases/tag/v14.0.0) - we should be on this version too based on the last tagged release:

https://github.com/shiftkey/desktop/blob/4b32c1e65dc6d6c6a7962df41f1316bfb78e6b26/package.json#L172

> That's the problem - we can control only from where it'll download electron, no way to make it use existing local files without downloading anything.

Let's see if we can get `spectron` and `electron-chromedriver` (which I believe is the last vestige of `electron-download` that's relevant to us) to also switch over to `@electron/get` if that's easier to interoperate with (I think that's what the core team wants to see projects using anyway).

EDIT: looks like the first upgrade has landed on `master` and will go out in the latest `electron-chromedriver` release https://github.com/electron/chromedriver/commit/3c22216af4df5b465215303f497ce31a6fdbcddb#diff-b9cfc7f2cdf78a7f4b91a753d10865a2. Then it would just be a matter of a new `spectron` upgrade to go with it.

**Comment by gasinvein** [comment] 2020-05-11 00:08
@shiftkey Thanks for clarification. Still, I'm pretty sure something it triggering electron (not chromedriver) download via electron-download. Can it be somehow caused by this?
https://github.com/shiftkey/desktop/blob/4b32c1e65dc6d6c6a7962df41f1316bfb78e6b26/package.json#L129

**Comment by shiftkey** [comment] 2020-05-11 00:12
I've been using the lockfile as that makes explicit what packages were being resolved.

I don't believe it's that package, because the version we have doesn't depend on either `electron-download` or `@electron/get`:

https://github.com/shiftkey/desktop/blob/527d9668c08b2ac4510389e3587ca8527d8b635e/yarn.lock#L289-L294

I believe it's this package:

https://github.com/shiftkey/desktop/blob/527d9668c08b2ac4510389e3587ca8527d8b635e/yarn.lock#L3496-L3502

**Comment by gasinvein** [comment] 2020-06-02 17:15
Seems like I was mistaken and actually it's other way around: `electron/get` doesn't look for cache path set by `electron_config_cache` env var (unlike `electron-download`, which did use it) electron/get#160

**Comment by malept** [comment] 2020-06-10 07:27
FYI, `electron-installer-flatpak` appears unmaintained, so I've been maintaining a fork at [`@malept/electron-installer-flatpak`](https://github.com/malept/electron-installer-flatpak), mostly for the purposes of integrating with Electron Forge.

**Comment by shiftkey** [comment] 2021-01-24 16:53
I was following up on the blockers for this offline only version and these were the two blockers:

> * There is no easy way to point electron-download to a pre-downloaded cache. I believe electron-get handles it better (at least it should respect `electron_config_cache` env var).

I've opened #423 which shows how we can upgrade `@electron/get` in a targeted way to get fixes for older versions where a dependency needs it, but we may need to look at upgrading `electron-chromedriver` (which may also require an `electron` upgrade) as that needed a separate fix https://github.com/electron/chromedriver/pull/74

> * node-sass must match `node` abi version (since it's used during build time), while other native modules must match electron's abi version. The tricky part is that since we build offline, node headers can't be downloaded on demand, only pointed to via `npm_config_nodedir` env var.

We no longer use `node-sass` in GitHub Desktop so hopefully this is no longer an issue.

**Comment by gasinvein** [comment] 2021-01-24 18:13
@shiftkey I think that in the meantime those blockers were somehow addressed on flatpak side: we've added "XDG mode" to the helper tool, so that it puts caches in `$XDG_CACHE_HOME` directory. And since most of the modern electron-related packages respect the XDG spec, we don't need to set neither `npm_config_nodedir` nor `electron_config_cache` anymore.
I've updated the flatpak-builder [manifest](https://github.com/gasinvein/flatpak-apps-staging/blob/com.github.shiftkey.GitHubDesktop/master/com.github.shiftkey.GitHubDesktop.yml) for Github Desktop with relevant changes.

**Comment by shiftkey** [comment] 2021-07-19 12:39
@advaithm has taken the time to provide offline packaging for Desktop that will be available from Flathub soon https://github.com/flathub/io.github.shiftey.Desktop

I'm going to close this out as resolved, even if it's being done outside this repository.

**Closed as completed by shiftkey** 2021-07-19 12:39 UTC
Labels: help wanted, infrastructure
