### ISSUE TITLE
https://snapcraft.io/github-desktop does not work on ubuntu

### ISSUE THREAD

**Issue by lav-patel** [shiftkey/desktop#183] opened 2019-10-10 19:48 UTC
## Description

https://snapcraft.io/github-desktop does not work on ubuntu

## Version

* GitHub Desktop: latest/beta 2.1.0-linux1

* Operating system: Ubuntu 18.04

## Steps to Reproduce

1. `step 1` sudo snap install --classic --beta github-desktop
2. `step 2` try to open it and it will not open
### Expected Behavior

application should open after clicking on icon
### Actual Behavior

application does not open after clicking on icon

**Comment by bshweta7** [comment] 2019-10-11 01:35
Just tried the same, had the same issue

**Comment by MattiaFailla** [comment] 2019-10-11 10:52
The problem seems to be here:

`/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy`

The snap package seems to include libglib-2.0.so.0 version 2.48.2 but It doesn’t include libgobject-2.0.so.0 though, despite it being needed by the github-desktop executable. That library use the g_date_copy symbol that doesn’t exist in the bundled libglib-2.0.so.0.

**Comment by immackay** [comment] 2019-10-16 02:13
Hi all,

See #163, there are instructions there for downgrading to 2.0.4 - hopefully this issue will be fixed in the next linux release

**Comment by nbarsch** [comment] 2019-10-22 14:50
As a workaround USE THE PREVIOUS VERSION:

To install the previous version (which works and tested bionic ubuntu 18.04 LTS AND 19.10 eoan) and remove the version you tried to install:

```
cd ~
wget https://github.com/shiftkey/desktop/releases/download/release-2.0.4-linux1/GitHubDesktop-linux-2.0.4-linux1.snap
snap remove github-desktop
snap install GitHubDesktop-linux-2.0.4-linux1.snap --classic --dangerous
```

**Comment by Midnex** [comment] 2019-10-30 22:32
Guess this would be why it is not working on Mint either. Hope this gets fixed soon. Will check into down grading now

**Comment by magdesign** [comment] 2019-10-31 15:24
as a workaround, use the .deb package from the release section: https://github.com/shiftkey/desktop/releases

**Comment by lav-patel** [comment] 2019-11-01 17:44
is it going to get fixed in the next release?

**Comment by ghost** [comment] 2019-11-02 10:18
I have the same problem but im using Ubuntu 19.04, and like u say when i click the icon nothing happens, even there no processes being ejecuted related to github desktop. And for example if in the terminal i type `github-desktop`,  the next pops up: "Violación de segmento (`core' generado)", its in spanish if anyone doesnt understand.

**Comment by kukaiN** [comment] 2019-12-22 09:59
Have the same problem with Debian

**Comment by shiftkey** [comment] 2020-02-07 19:10
Closing this out as a duplicate of #163.

The `deb` installer is recommended until we can get to the bottom of that issue.

**Closed as completed by shiftkey** 2020-02-07 19:10 UTC
Labels: installers/snap
