### ISSUE TITLE
Cannot clone or fetch - application waits endlessly

### ISSUE THREAD

**Issue by BorisBrock** [shiftkey/desktop#628] opened 2021-11-19 19:19 UTC
I just installed Github Desktop 2.9.4 on Linux Mint Cinnamon 20.2. When I try to clone a repostory from my Gitea server, Github Desktop gets stuck with "Cloning...". The same thing happens when I try to fetch on an already existing repository.

![GithubDesktop](https://user-images.githubusercontent.com/5222025/142679606-ec004d7b-cacf-4bb7-bf37-c6442bf3f96c.png)

The app does not freeze though. I can still access the menu for example. It just never finishes the operation.

When I try the same operations from the command line (git clone...), it works perfectly.

**Comment by shiftkey** [comment] 2021-11-22 13:47
@VanKurt thanks for the report.

Please check the logs files at `~/.config/GitHub Desktop/logs/` (organized by date) to see if there's any clues about the underlying Git operation. The Desktop app uses an embedded version of Git and perhaps there's some difference that's causing it to fail for your setup.

**Comment by BorisBrock** [comment] 2021-11-22 18:31
> Please check the logs files at `~/.config/GitHub Desktop/logs/` (organized by date) to see if there's any clues about the underlying Git operation. The Desktop app uses an embedded version of Git and perhaps there's some difference that's causing it to fail for your setup.

The path you mentioned does not exist on my machine. However I found some log files here:

/home/vankurt/.var/app/io.github.shiftey.Desktop/config/GitHub Desktop/logs

I deleted them all, then executed a fetch operation in GitHub Desktop and waited for a few minutes. This is the result:

> 2021-11-22T18:24:01.293Z - info: [ui] [AppStore] loading 1 repositories from store
> 2021-11-22T18:24:01.421Z - info: [ui] launching: 2.9.4-linux1 (Linux 5.4.0-90-generic)
> 2021-11-22T18:24:01.421Z - info: [ui] execPath: '/app/github-desktop/github-desktop'
> 2021-11-22T18:24:01.889Z - info: [ui] Stats reported.

At least for me this does not look very helpful.

**Comment by shiftkey** [comment] 2021-11-22 21:42
> The path you mentioned does not exist on my machine. However I found some log files here:
>
> `/home/vankurt/.var/app/io.github.shiftey.Desktop/config/GitHub Desktop/logs`

Ah, this looks like the Flatpak installer. 

> At least for me this does not look very helpful.

I was hoping to see a Git operation started and/or details about why it might be stuck in the background. The big area I was hoping to see some clues about is authentication - you mentioned Gitea but no indication of whether you need to authenticate to access it, or whether you were prompted by the app to do this as part of the cloning operation.

There's a bunch of context here about how the app uses git, and it's not using your system-installed git so that's my best guess at the moment about why it might start the process but isn't completing. 

If you try closing the app does anything get flushed to the logs from this Git operation?

**Comment by BorisBrock** [comment] 2021-11-23 08:08
I just did a test with a fresh Linux Mint 20.2 installation in a virtual machine.
There seem to be two versions of GitHub Desktop in the app manager:

- A Flatpack package (version 2.9.4)
- A "regular" package (version 2.9.3)

Just as on my desktop PC, the Flatpack version hangs when cloning a repo. So this behavior seems to be reproducible.
The "regular" package on the other hand works perfectly. So it could either be a version problem (2.9.3 vs 2.9.4) or a package problem (Flatpack vs. "regular").

**Comment by shiftkey** [comment] 2021-11-23 13:41
Can you please test the [2.9.4](https://github.com/shiftkey/desktop/releases/tag/release-2.9.4-linux1) DEB release from this repository and confirm that works as expected? If that's working, we can dig into what changes the Flatpak version is adding that might be a factor here...

**Comment by BorisBrock** [comment] 2021-11-23 18:30
I just tested the 2.9.4 deb. It works flawlessly.
So the problem seems to exist only in the Flatpack version.

**Comment by shiftkey** [comment] 2021-11-23 18:34
It may be necessary to move this to https://github.com/flathub/io.github.shiftey.Desktop which is the Flathub-specific repository. 

cc @Lunarequest for visibility

**Comment by Lunarequest** [comment] 2021-11-25 14:42
Sorry for not responding sooner. I have been a bit busy with uni work. I will try and reproduce and fix the issue over the weekend

**Comment by hholst80** [comment] 2021-11-26 10:02
The same problem exists inside the app with the Pull/fetch. It locks like before (on push) but now only on fetch. I am using the rpm.
```
$ more 2021-11-26.desktop.production.log                                                                                                                                                                                            /home/om/.config/GitHub Desktop/logs 
2021-11-26T01:23:00.783Z - info: [ui] [BranchPruner] Last prune took place in 20 hours - skipping
2021-11-26T05:23:00.759Z - info: [ui] [BranchPruner] Last prune took place in 16 hours - skipping
2021-11-26T08:29:55.860Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 34550.596s)
2021-11-26T09:23:00.757Z - info: [ui] [BranchPruner] Last prune took place in 12 hours - skipping
2021-11-26T10:00:20.689Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 3504.510s)
2021-11-26T10:00:21.062Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: centsoft - hholst80 (has token)
```

EDIT: this was with 2.9.0 I will try with 2.9.4 and see if I can repro.

Another update: I am pleased to see that this seems to work in 2.9.4 - at least for the RPM build!

**Comment by Lunarequest** [comment] 2022-01-03 16:08
I had some free time and tried to reproduce this issue and am unable too. if someone can get link a repo where this issue occurs consistently I am more then willing to fix it

**Comment by shiftkey** [comment] 2022-04-03 18:17
Closing this out due to inactivity and lack of repro steps. 

Please submit a new issue if you have more information about this issue.

**Closed as completed by shiftkey** 2022-04-03 18:17 UTC
Labels: unclear, bug, installers/flatpak
