### ISSUE TITLE
White screen at launch of the app in Ubuntu

### ISSUE THREAD

**Issue by fredboxebeld** [shiftkey/desktop#963] opened 2023-11-28 11:04 UTC
### The problem

When I launch GitHub Desktop the app launches, but after a few seconds the window of the app becomes completely white and I cannot do anything more (see attached picture)

### Release version

26.2.4

### Operating system

Ubuntu 22.04.3 LTS

### Steps to reproduce the behavior

1. Click on "Show applications"
2. Select the GitHub Desktop app
3. Wait a few seconds
Now the screen is white (as shown in the attached picture)

### Log files

2023-11-28T10:41:13.955Z - info: [ui] [AppStore] loading 7 repositories from store
2023-11-28T10:41:13.959Z - info: [ui] [AppStore] found account: {username} ({username})
2023-11-28T10:41:14.210Z - info: [ui] launching: 3.3.5-linux1 (Linux 6.2.0-37-generic)
2023-11-28T10:41:14.210Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
2023-11-28T10:41:14.344Z - info: [ui] Subscribed '{username}' to Alive channel
2023-11-28T10:41:14.488Z - info: [ui] Stats reported.
2023-11-28T10:41:39.795Z - info: [ui] Subscribed '{username}' to Alive channel
2023-11-28T10:41:39.798Z - info: [ui] [AppStore] loading 7 repositories from store
2023-11-28T10:41:39.798Z - info: [ui] [AppStore] found account: {username} ({username})
2023-11-28T10:41:39.954Z - info: [ui] launching: 3.3.5-linux1 (Linux 6.2.0-37-generic)
2023-11-28T10:41:39.954Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
2023-11-28T10:42:50.582Z - info: [ui] [AppStore] loading 7 repositories from store
2023-11-28T10:42:50.584Z - info: [ui] [AppStore] found account: {username} ({username})
2023-11-28T10:42:50.731Z - info: [ui] launching: 3.3.5-linux1 (Linux 6.2.0-37-generic)
2023-11-28T10:42:50.731Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
2023-11-28T10:42:50.951Z - info: [ui] Subscribed '{username}' to Alive channel
2023-11-28T10:52:57.983Z - info: [ui] [AppStore] loading 7 repositories from store
2023-11-28T10:52:57.985Z - info: [ui] [AppStore] found account: {username} ({username})
2023-11-28T10:52:58.134Z - info: [ui] launching: 3.3.5-linux1 (Linux 6.2.0-37-generic)
2023-11-28T10:52:58.134Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
2023-11-28T10:52:58.336Z - info: [ui] Subscribed '{username}' to Alive channel

### Screenshots

![image](https://github.com/shiftkey/desktop/assets/149372906/005f00a8-e34b-4fec-8063-5090ba53eb46)

**Comment by iso4free** [comment] 2023-11-28 11:18
The same is on Linux Mint 21.2 Cinnamon.

**Comment by barbalex** [comment] 2023-11-28 11:19
The same happens on Pop OS 22.04

**Comment by barbalex** [comment] 2023-11-28 11:20
Duplicate of  https://github.com/shiftkey/desktop/issues/958

**Comment by shiftkey** [comment] 2023-11-28 12:22
Duplicate of https://github.com/shiftkey/desktop/issues/958, please re-test with the latest release https://github.com/shiftkey/desktop/releases/tag/release-3.3.5-linux2 (has to be installed manually for now) and see if it resolves for your setup.

**Closed as not planned by shiftkey** 2023-11-28 12:22 UTC
