### ISSUE TITLE
Installation Command not working in Readme.md

### ISSUE THREAD

**Issue by vishalkrishnaagQwy** [shiftkey/desktop#1081] opened 2024-06-09 05:20 UTC
### The problem

sudo rpm --import https://rpm.packages.shiftkey.dev/gpg.key
sudo sh -c 'echo -e "[shiftkey-packages]\nname=GitHub Desktop\nbaseurl=https://rpm.packages.shiftkey.dev/rpm/\nenabled=1\ngpgcheck=1\nrepo_gpgcheck=1\ngpgkey=https://rpm.packages.shiftkey.dev/gpg.key" > /etc/zypp/repos.d/shiftkey-packages.repo'

when running it in terminal iam getting a response gpg: no valid OpenPGP data found.

### Release version

3.3.18

### Operating system

ubuntu 24.04

### Steps to reproduce the behavior

1. open a terminal 
2. copy first key  adding command from readme.md 
3.  wget -qO - https://apt.packages.shiftkey.dev/gpg.key | gpg --dearmor | sudo tee /usr/share/keyrings/shiftkey-packages.gpg > /dev/null
4. you will get error gpg: no valid OpenPGP data found.

**Comment by Thelvaen** [comment] 2024-06-10 07:42
most likely duplicate with #1080.

**Comment by shiftkey** [comment] 2024-07-01 18:14
Duplicate of #1080

**Closed as completed by shiftkey** 2024-07-01 18:14 UTC
