### ISSUE TITLE
GitHub desktop pushing changes very slowly on Chrome OS Linux

### ISSUE THREAD

**Issue by Bobby99as** [shiftkey/desktop#488] opened 2021-04-29 17:20 UTC
### Describe the bug
Taking forever to push origin

### Version & OS
2.6.3 Chrome OS Linux

### Steps to reproduce the behavior
Clone your repository to internal storage
Make any type of change to any of the files in it
Click push changes to origin
You'll see that it takes forever to push the simple change
Expected behavior
It uploads in a few seconds

### Actual behavior
It takes about a couple minutes

### Screenshots
N/A

### Logs
I don't have any but if they're needed I can upload some

### Additional context
I've noticed that it takes a couple of seconds to upload my changes when I have GitHub desktop installed on my Windows computer but when I work on my Chromebook and I go to push the changes on it. it takes about a couple of minutes.

**Comment by K0-RR** [comment] 2021-04-29 18:04
Duplicate of https://github.com/shiftkey/desktop/issues/329

**Comment by shiftkey** [comment] 2021-04-29 18:23
Seconding @RDKRACZ - please follow along with #329

**Closed as completed by shiftkey** 2021-04-29 18:23 UTC

**Comment by Bobby99as** [comment] 2021-04-29 18:27
Its old and does not seem to get fixed it does not take 1 year to fix a small bug @shiftkey

**Comment by K0-RR** [comment] 2021-04-29 18:59
How do you know it's a small bug? Maybe it takes so much time because the dev(s) doesn't know what is causing this and is busy with more important bugs (take a look at commits)?
The walkaround is described in issue 329. I’m sure there is no need to remind the dev about this issue since the original one gets new comments from time to time and is still open. Also if you know how to fix it you can always submit pr. Nobody is forcing you to use this ported for free app 🙂

**Comment by shiftkey** [comment] 2021-04-29 19:25
> Its old and does not seem to get fixed it does not take 1 year to fix a small bug @shiftkey

I disagree that this is a small bug, and find comments like this unhelpful.

Identifying the area required me remembering about Node internals and how Node interacts with child processes to get close to the issue. At the time any attempt to test a debug version of the app or use a debug build of Electron - so I could see at a lower level what's happening - would cause the problem to disappear. So that's why it's stalled - I burned several weekends trying to confirm my theory without success.

And while that issue has a lot of comments from users encountering it, and committing is an important part of the app, there are known workarounds. 

I'm no longer actively contributing to GitHub Desktop as part of my day job, so I probably wasn't tracking where this was introduced between all the moving parts that make up this project, but I try to set aside time to keep this fork up to date with the latest changes from the main project. I'd love to fix this bug, and would happily review a PR from the community if they can identify the fix, but it hasn't happened yet.
