### ISSUE TITLE
Crash after few seconds

### ISSUE THREAD

**Issue by tymmesyde** [shiftkey/desktop#969] opened 2023-12-01 13:37 UTC
### The problem

Few seconds after launch, the UI freeze and shows a blank page

Here is what the logs says:
```Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed```

### Release version

3.3.5

### Operating system

Fedora 39

### Steps to reproduce the behavior

Open GitHub Desktop

### Log files

```
[2:1201/143212.451849:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Gtk-Message: 14:32:12.602: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:32:12.602: Failed to load module "pk-gtk-module"
Gtk-Message: 14:32:12.602: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:32:12.602: Failed to load module "pk-gtk-module"
[2:1201/143212.616392:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:1201/143212.616419:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at U (/app/github-desktop/resources/app/main.js:2:211774)
    at BrowserWindow.<anonymous> (/app/github-desktop/resources/app/main.js:2:216319)
    at BrowserWindow.emit (node:events:525:35)
```

### Screenshots

![image](https://github.com/shiftkey/desktop/assets/7889816/66810279-84d5-4e2e-8065-bea82437795b)

**Comment by shiftkey** [comment] 2023-12-01 19:13
Duplicate of https://github.com/shiftkey/desktop/issues/958, please re-test with the latest release https://github.com/shiftkey/desktop/releases/tag/release-3.3.5-linux2 (has to be installed manually for now) and see if it resolves for your setup.

**Closed as not planned by shiftkey** 2023-12-01 19:13 UTC
