### ISSUE TITLE
Authentication still fails in 1.0.11 RC3

### ISSUE THREAD

**Issue by AluminiumTech** [shiftkey/desktop#18] opened 2017-12-19 13:20 UTC
Description: Trying to push any commits will fail and it'll provide the reason of authentication or lack thereof.

![permissions](https://user-images.githubusercontent.com/14107316/34158937-566a837c-e502-11e7-9c19-ebc8fe28bd99.png)

### Version

**GitHub Desktop version:** 1.0.11 for Linux RC3

**OS version:** Ubuntu 17.10 with latest updates,

### Steps to Reproduce

1. Install RC3
2. Try to commit any changes and then push them to a repo you have permissions on.

**Expected behavior:** Pushes commit to the repository.

**Actual behavior:** Provides error message and doesn't push changes.

**Reproduces how often:** Every Time

### Logs
[2017-12-19.desktop.production.log](https://github.com/shiftkey/desktop/files/1571748/2017-12-19.desktop.production.log)

**Comment by shiftkey** [comment] 2017-12-19 22:31
@AluminiumTech the logs suggest your token is stored and retrieved correctly, but it's also weird that there's no push errors in the log. Could you open up the Developer Tools (<kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>I</kbd>) when this fails and check the Console tab for any raw Git errors?

**Comment by AluminiumTech** [comment] 2017-12-25 12:36
There's apparently no errors in Dev Tools in the Console Tab when i do that.

**Comment by shiftkey** [comment] 2019-05-12 15:22
I'm going to close this out because I don't have the bandwidth currently to investigate what this might have been - apologies @AluminiumTech!

I was hoping to see the underlying Git messages in the log output but the logs didn't indicate there was a problem with pushing, so I'm not sure what else I can do here aside from see whether this is still reproducible on a later version of the app (and would yield more information).

**Closed by shiftkey** 2019-05-12 15:22 UTC
Labels: unclear
