### ISSUE TITLE
UI actions don't complete until application window de-activated and re-activated

### ISSUE THREAD

**Issue by CantStopMyBrain** [shiftkey/desktop#573] opened 2021-07-31 11:47 UTC
### Describe the bug

Actions such as commit, push, and fetch appear to take "forever" -- the UI displays the "busy" or "in-progress" animations indefinitely. As soon as I minimize or activate/de-activate the GitHub Desktop window, it immediately terminates the "busy" animations and displays the completed action. I think the action is actually finished immediately (more or less) but the UI is hung. If I start an action and quickly flip to some other window and back it "completes" right away.

### Version & OS

GitHub Desktop Version 2.8.1-linux1

uname -a
Linux <myhostname> 5.11.0-7620-generic #21~1626191760~20.04~55de9c3~dev-Ubuntu SMP Tue Jul 20 18:02:09  x86_64 x86_64 x86_64 GNU/Linux

### Steps to reproduce the behavior

1. Prepare a commit
2. Click the "Commit to master" button
3. Wait... animations run and run and run (I've only waited a few minutes; maybe they eventually terminate on their own)
4. Ditto for Push and Fetch operations

In contrast:
1. Prepare a commit
2. Click the "Commit to master" button
3. activate some other application window
4. re-activate the GitHub Desktop window -- the action "completes" (or at least the UI displays completion)
5. ditto for Push and Fetch

### Expected behavior

UI should show completion without having to de-activate/re-activate the application window.

### Actual behavior

See above

**Comment by K0-RR** [comment] 2021-07-31 12:25
>Version 2.8.1-linux1

Outdated version

>I think the action is actually finished immediately (more or less) but the UI is hung

From my testing, that's not true. It won't begin pushing without refreshing the UI.

Duplicate of https://github.com/shiftkey/desktop/issues/329 and more.

**Comment by CantStopMyBrain** [comment] 2021-07-31 16:44
Apologies for not being on the latest version -- I thought I had just updated to the latest but am now realizing that was on a second laptop sitting next to me here. I'll try to be more careful in the future. Thanks for the quick response -- #329 indeed sounds like the same issue.

However: I've updated to latest (release-2.9.0-linux4) and while commits now happen w/o intervention, the behavior I described previously still occurs for push and fetch: the spinning arrows go indefinitely and the progress bar doesn't budge... it can go on like this for many minutes, but the moment I click back after clicking away to another app window, the action completes on the spot.

Perhaps some dependency needs updating? I've only updated GitHub desktop by downloading the .deb file and installing... should that take care of all depdencies?

**Comment by shiftkey** [comment] 2021-07-31 19:12
> However: I've updated to latest (release-2.9.0-linux4) and while commits now happen w/o intervention, the behavior I described previously still occurs for push and fetch: the spinning arrows go indefinitely and the progress bar doesn't budge... it can go on like this for many minutes, but the moment I click back after clicking away to another app window, the action completes on the spot.

@CantStopMyBrain this feels like #508 which I theorize is related to Git operations which require authentication. Haven't dug into it, but if you're also interacting with private repositories while seeing these issues I think it's the same root cause there.

**Comment by hholst80** [comment] 2021-08-05 12:45
Same problem in 2.9.0. Pushes can stall for many minutes unless I fiddle the UI (specifically, between history and changes)

**Comment by hholst80** [comment] 2021-08-05 12:46
BTW, @CantStopMyBrain are you by any chance using VS Code?

I am getting these warnings when I push from CLI it might be related to some tooling that have injected itself like a virus. Modus operandi for any vscode but IDK I could be wrong (I am using a VSCode plugin for "remote containers" so it is not a wild guess).

```
$ git push
Remote-Containers CLI: RPC pipe not configured. Message: {"command":"fill","stdin":"protocol=https\nhost=github.com\n"}
Remote-Containers CLI: RPC pipe not configured. Message: {"command":"approve","stdin":"protocol=https\nhost=github.com\nusername=YYY\npassword=XXX\n"}
Remote-Containers CLI: RPC pipe not configured. Message: {"command":"fill","stdin":"protocol=https\nhost=github.com\n"}
Remote-Containers CLI: RPC pipe not configured. Message: {"command":"approve","stdin":"protocol=https\nhost=github.com\nusername=YYY\npassword=XXX\n"}
Enumerating objects: 16, done.
```

**Comment by shiftkey** [comment] 2021-08-13 16:14
Let's move this to https://github.com/shiftkey/desktop/issues/508 as I believe it's the same root cause

**Closed as completed by shiftkey** 2021-08-13 16:14 UTC
