### ISSUE TITLE
github desktop

### ISSUE THREAD

**Issue by vineeth765** [shiftkey/desktop#196] opened 2020-01-06 12:02 UTC
git hub desktop app is not opening

**Comment by JeroenBos** [comment] 2020-01-14 19:55
Same. Ubuntu 18.04.
First time install (`sudo snap install github-desktop --beta --classic`). Opening win+github+enter does nothing. 
In terminal, `github-desktop` results in `/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy`

**Comment by mcooper52590** [comment] 2020-01-15 16:53
Same here.  Ubuntu 18.04.  Looks like a spelling error.  libgobject-2.0.so.0 isn't available, but libgio-2.0.so.0 is.

**Comment by saurabhrathour** [comment] 2020-01-16 08:30
> Same. Ubuntu 18.04.
> First time install (`sudo snap install github-desktop --beta --classic`). Opening win+github+enter does nothing.
> In terminal, `github-desktop` results in `/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy`

As latest version of it, is not working, you can use the previous version, follow this following comment:
https://github.com/shiftkey/desktop/issues/163#issuecomment-525140265

**Comment by claudchan** [comment] 2020-01-19 13:38
Same issue here. Github Desktop not openning.
Tested in Zorin OS and Elementary OS.

**Comment by claudchan** [comment] 2020-01-19 14:59
Download / downgrade to version 2.0.4 works fine:
https://github.com/shiftkey/desktop/issues/163#issuecomment-525140265

Download version 2.0.4 from [here](https://github.com/shiftkey/desktop/releases/download/release-2.0.4-linux1/GitHubDesktop-linux-2.0.4-linux1.snap)
```
cd ~/Downloads
snap remove github-desktop
snap install GitHubDesktop-linux-2.0.4-linux1.snap --classic --dangerous
```

**Comment by yongen9696** [comment] 2020-02-03 01:59
> Download / downgrade to version 2.0.4 works fine:
> [#163 (comment)](https://github.com/shiftkey/desktop/issues/163#issuecomment-525140265)
> 
> Download version 2.0.4 from [here](https://github.com/shiftkey/desktop/releases/download/release-2.0.4-linux1/GitHubDesktop-linux-2.0.4-linux1.snap)
> 
> ```
> cd ~/Downloads
> snap remove github-desktop
> snap install GitHubDesktop-linux-2.0.4-linux1.snap --classic --dangerous
> ```

Thanks!

**Comment by shiftkey** [comment] 2020-02-07 19:10
Closing this out as a duplicate of #163.

The `deb` installer is recommended until we can get to the bottom of that issue.

**Closed as completed by shiftkey** 2020-02-07 19:10 UTC
Labels: installers/snap
