### ISSUE TITLE
Committing takes a while even when it is few lines and a single file.

### ISSUE THREAD

**Issue by omerasif57** [shiftkey/desktop#482] opened 2021-04-18 15:51 UTC
**Operating System/Distribution**
Ubuntu 20.04.1 LTS

**Which version of the app?**
2.6.3-linux1

**Which installer type?**
.deb

**What happened?**

Committing takes a while even when it is few lines and a single file. Is it normal because vs code or android studio is comparatively quick. 
If anyone has observed this? 
Please advise.

**Comment by K0-RR** [comment] 2021-04-18 16:27
Duplicate of #329

**Comment by shiftkey** [comment] 2021-04-18 16:36
Please follow along with #329

**Closed as completed by shiftkey** 2021-04-18 16:36 UTC
