### ISSUE TITLE
create commit sometimes doesn't complete without switching away from app

### ISSUE THREAD

**Issue by khvorov45** [shiftkey/desktop#329] opened 2020-08-27 23:48 UTC
### Describe the bug

Commit loading appears to never end until you click out of the window and then click back in.

<details>
<summary>demo</summary>
<img src="https://user-images.githubusercontent.com/44919476/91505558-37eab300-e913-11ea-8279-8301adfa4456.gif" alt="Description of what the gif shows">
</details>

### Version & OS

Version 2.5.4-linux1
OS: Linux Mint 20

**Comment by shiftkey** [comment] 2020-08-29 15:05
@khvorov45 thanks for the report. I've been able to reproduce this myself, but it'll take a bit to dig into why the commit completes but the UI doesn't update (until you switch away and focus the app again).

**Comment by bompus** [comment] 2020-08-29 20:42
I experienced this as well on 2.5.3 but then reformatted my system and it didn't happen again, even on 2.5.4 until today I noticed it pop up again.. not sure what triggers this weirdness.

**Comment by shiftkey** [comment] 2020-08-30 15:30
I believe something's change with how Electron (or NodeJS) uses `child_process.execFile` on Linux when a command needs to provide `stdin`. It seems to be just these types of operations that delay until _something else happens_ (like onblur/onfocus of the app) to cause the callbacks to fire.

The fact that this has been seen on 2.5.3 (Electron 7) and 2.5.4 (Electron 9) makes me wonder if we need to revisit the handling of processes inside `dugite` (which contains our Git plumbing work relevant to this area) for this situation.

**Comment by charitarthchugh** [comment] 2020-08-31 16:29
This also happened to me. I also found that I had to fetch origin for it to commit if I did not leave the app. v2.5.4.

**Comment by MrTruth0** [comment] 2020-08-31 20:51
I'm having the same Problem, and i noticed that sometimes when i do a commit the "Summary" doesn't being cleaned

**Comment by daniel-halodi** [comment] 2020-09-15 22:46
I'm having the same problem. When just hitting "commit to branch" it takes forever, but when clicking outside window and back it happens instantly.

Version 2.5.4-linux1
Ubuntu 18.04.5 LTS 64-bit
Running on a modern High end computer with Rysen 9 3900x CPU, Nvidia 1080 TI GPU, PciE4 M.2 SSD, 32GB RAM

**Comment by atjn** [comment] 2020-10-02 23:18
I'm having the same issue. I make it update by resizing the window.

**Comment by NuzzasKatla** [comment] 2020-10-05 21:06
Also not working on Ubuntu 20.04.1 LTS, probably all Debian based distros

**Comment by dwbapst** [comment] 2020-10-25 16:50
I'm having the same issue, also on Linux Mint. (Apologies if that isn't very helpful -- thanks for y'all's hard work keeping us Linux user from having to type git commands!)

**Comment by Tonymunyao12** [comment] 2020-10-25 20:02
Hello David,

I'm hoping that github Desktop support team will sort the issue out.
There is a time, the commit option took less time in actually making the
commit.

**Comment by vinnom** [comment] 2020-10-30 11:51
Not just commiting, but discarding changes also requires "double alt+tab".

Arch linux:
> $ uname -rsmo
Linux 5.9.1-zen2-1-zen x86_64 GNU/Linux

github-desktop package:
> $ proc github-desktop
aur/github-desktop-git r26627.3461639c7-1 (+5 0.00) 
    GUI for managing Git and GitHub.
aur/github-desktop-bin 2.5.4-1 (+22 3.57) (Installed)
    GUI for managing Git and GitHub.
aur/github-desktop 2.5.4-1 (+31 1.54) 

![Captura de tela de 2020-10-30 08-46-43](https://user-images.githubusercontent.com/11577103/97701988-05814180-1a8d-11eb-86f8-1cf56df2e745.png)

**Comment by mariocalin** [comment] 2020-11-13 14:20
The same is happening to me in Kubuntu. When I try to swicth the window or do something with it it completes the commit. 

_Distro info
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal_

**Comment by tienthanh2509** [comment] 2020-11-17 09:40
Same issues to me.

Linux Mint 20
Github desktop version: 2.5.7-linux1
![ezgif-2-066eaff70df4](https://user-images.githubusercontent.com/1713444/99372686-1e924b00-28f3-11eb-8546-682d10a49fec.gif)

```
2020-11-17T09:08:47.393Z - info: [ui] proxy url not resolved, protocol not supported
2020-11-17T09:08:49.877Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.483s)
2020-11-17T09:08:49.913Z - info: [ui] Background fetch for 7 repositories took 31.175sec
2020-11-17T09:23:49.981Z - info: [ui] Background fetch for 7 repositories took 0.051sec
2020-11-17T09:24:09.685Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 8.062s)
2020-11-17T09:24:10.738Z - info: [ui] Executing applyPatchToIndex: git apply --cached --unidiff-zero --whitespace=nowarn - (took 1.049s)
2020-11-17T09:24:10.971Z - info: [ui] [Timing] Action 'create commit' for 'monitoring' took 9.356s
2020-11-17T09:24:16.808Z - info: [main] opening in browser: https://desktop.github.com/release-notes/
2020-11-17T09:28:39.153Z - info: [ui] [AppStore] loading 7 repositories from store
2020-11-17T09:28:39.604Z - info: [ui] launching: 2.5.7-linux1 (Linux 5.4.0-54-generic)
2020-11-17T09:28:39.604Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
2020-11-17T09:29:06.173Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 14.121s)
2020-11-17T09:29:06.986Z - info: [ui] [Timing] Action 'create commit' for 'monitoring' took 14.979s
2020-11-17T09:32:22.116Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 6 repositories took 0.2s of which 0.0s paused, total 0.2s
2020-11-17T09:33:02.119Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 5.371s)
2020-11-17T09:33:02.253Z - info: [ui] [Timing] Action 'create commit' for 'monitoring' took 5.529s
2020-11-17T09:33:55.788Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 4.140s)
2020-11-17T09:33:55.937Z - info: [ui] [Timing] Action 'create commit' for 'monitoring' took 4.308s
2020-11-17T09:39:26.143Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 8.345s)
2020-11-17T09:39:26.283Z - info: [ui] [Timing] Action 'create commit' for 'monitoring' took 8.528s
```

The commit command  only run when changing tab or switch windows

```
2020-11-17T09:39:26.143Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 8.345s)
2020-11-17T09:39:26.283Z - info: [ui] [Timing] Action 'create commit' for 'monitoring' took 8.528s
```

**Comment by JonathanBrouwer** [comment] 2020-11-23 15:58
Same issue
Version 2.5.7-linux1
Kernel 5.10.0-1-MANJARO
Running Manjaro KDE, everything up-to-date

**Comment by sgse** [comment] 2020-12-01 20:41
First, thank you for this wonderful and helpful software :-) 
***
I'm having the same issue.
~~~
OS: Garuda Linux x86_64
Kernel: 5.9.11-zen2-1-zen 
~~~
Github desktop version: 2.5.7-linux1

**Comment by Jick-study** [comment] 2020-12-07 05:28
> 我也遇到同样的问题。
> 
> Linux Mint 20
> Github桌面版本：2.5.7-linux1
> ![ezgif-2-066eaff70df4](https://user-images.githubusercontent.com/1713444/99372686-1e924b00-28f3-11eb-8546-682d10a49fec.gif)
> 
> ```
> 2020-11-17T09:08:47.393Z - info: [ui] proxy url not resolved, protocol not supported
> 2020-11-17T09:08:49.877Z - info: [ui] Executing fetch: git -c credential.helper= fetch --progress --prune origin (took 2.483s)
> 2020-11-17T09:08:49.913Z - info: [ui] Background fetch for 7 repositories took 31.175sec
> 2020-11-17T09:23:49.981Z - info: [ui] Background fetch for 7 repositories took 0.051sec
> 2020-11-17T09:24:09.685Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 8.062s)
> 2020-11-17T09:24:10.738Z - info: [ui] Executing applyPatchToIndex: git apply --cached --unidiff-zero --whitespace=nowarn - (took 1.049s)
> 2020-11-17T09:24:10.971Z - info: [ui] [Timing] Action 'create commit' for 'monitoring' took 9.356s
> 2020-11-17T09:24:16.808Z - info: [main] opening in browser: https://desktop.github.com/release-notes/
> 2020-11-17T09:28:39.153Z - info: [ui] [AppStore] loading 7 repositories from store
> 2020-11-17T09:28:39.604Z - info: [ui] launching: 2.5.7-linux1 (Linux 5.4.0-54-generic)
> 2020-11-17T09:28:39.604Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
> 2020-11-17T09:29:06.173Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 14.121s)
> 2020-11-17T09:29:06.986Z - info: [ui] [Timing] Action 'create commit' for 'monitoring' took 14.979s
> 2020-11-17T09:32:22.116Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 6 repositories took 0.2s of which 0.0s paused, total 0.2s
> 2020-11-17T09:33:02.119Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 5.371s)
> 2020-11-17T09:33:02.253Z - info: [ui] [Timing] Action 'create commit' for 'monitoring' took 5.529s
> 2020-11-17T09:33:55.788Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 4.140s)
> 2020-11-17T09:33:55.937Z - info: [ui] [Timing] Action 'create commit' for 'monitoring' took 4.308s
> 2020-11-17T09:39:26.143Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 8.345s)
> 2020-11-17T09:39:26.283Z - info: [ui] [Timing] Action 'create commit' for 'monitoring' took 8.528s
> ```
> 
> commit命令仅在更改选项卡或切换窗口时运行
> 
> ```
> 2020-11-17T09:39:26.143Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 8.345s)
> 2020-11-17T09:39:26.283Z - info: [ui] [Timing] Action 'create commit' for 'monitoring' took 8.528s
> ```

我和你有一样的问题，所以我将版本回退到了  Version 2.5.3-linux1

**Comment by krushnaj** [comment] 2020-12-18 17:17
@shiftkey I noticed that the latest release is working fine and I do not have to switch apps to complete commits or discard changes.

### Version & OS
**Version**: 2.6.1 Linux RC1
**OS**: Ubuntu 20.04

**Comment by shiftkey** [comment] 2020-12-18 17:21
@krushnaj I'm seeing the behaviour change with the latest version, but I don't believe this is completely resolved.

For committing one file out of several in the working directory in a small repository I see a lot of time spent in `updateIndex`:

```
2020-12-18T17:19:15.647Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 5.990s)
2020-12-18T17:19:15.809Z - info: [ui] [Timing] Action 'create commit' for 'private-repo' took 6.169s
```

So while this feels like an improvement, I'm not ready to close this out just yet.

**Comment by krushnaj** [comment] 2020-12-18 17:26
@shiftkey Yes. I also noticed that it isn't as quick as it used to be in the previous version. But just wanted to point that the latest version worked for committing without switching apps.

**Comment by charitarthchugh** [comment] 2020-12-18 18:04
@shiftkey @krushnaj 
That is interesting. I have not tested with changing app focus but I still have to press fetch origin for it to commit. Same version, Pop! 20. 10

**Comment by abd3lraouf** [comment] 2020-12-22 16:56
@krushnaj The problem still exists. committing needs focus change to another app for it to complete.

I'm on Ubuntu 20.10

**Comment by cethol** [comment] 2021-01-06 12:30
I am having same issue, i tried to leave the loading and not clicking anything, it takes more than 100 seconds to complete. This is my log.

```
2021-01-06T12:17:49.534Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 2 repositories took 8.5s of which 32.2s paused, total 40.7s
2021-01-06T12:20:04.281Z - info: [ui] Executing updateIndex: git update-index --add --remove --replace -z --stdin (took 130.791s)
```

![image](https://user-images.githubusercontent.com/2105802/103768681-87758400-5055-11eb-80be-a3064b05b9f4.png)

@shiftkey

**Comment by kvz** [comment] 2021-01-15 14:26
Same issue on the latest version of GH Desktop as well as the latest Ubuntu as of today.

**Comment by johannesschobel** [comment] 2021-01-18 07:57
I noticed, that this only holds true for certain files-types (or repositories)
I have another repository containing `*.tex` files for research manuscripts. Committing `*.tex` files is blazingly fast.

**Comment by lgarczyn** [comment] 2021-01-20 11:43
Same issue on ubuntu 20.04.1 LTS and github desktop Version 2.5.4-linux1

**Comment by WernerLuiz92** [comment] 2021-01-28 04:29
I am having this exact same problem.
OS - Ubuntu 20.04.1 LTS
Version - 2.6.2-linux1

**Comment by askgh** [comment] 2021-03-16 06:52
is there a plan to fix this problem?

**Comment by shiftkey** [comment] 2021-03-16 16:50
> is there a plan to fix this problem?

Not currently, due to lack of time to investigate and a known workaround. This context still feels relevant but the fact that I've not been able to reproduce it in development mode has made it harder to isolate where this is lurking: https://github.com/shiftkey/desktop/issues/329#issuecomment-683434326

**Comment by francescoinfante** [comment] 2021-04-06 22:42
This solves the issue:
https://github.com/francescoinfante/dugite/pull/1/files
Unsure yet why, anyone has an idea?

**Comment by danielgoodwin97** [comment] 2021-04-21 16:53
If this is driving anybody else crazy, then the last build that isn't having this issue is [2.5.3 Linux RC1](https://github.com/shiftkey/desktop/releases/tag/release-2.5.3-linux1) which was before the Electron 9 upgrade.

It's not a great solution, but it's stopped me from wanting to rip my hair out. :man_shrugging:

**Comment by khickel** [comment] 2021-05-06 17:49
FYI I'm still having this issue with version 2.8.0-linux1, on RHEL 8.  Clicking on another window right after I commit/fetch/pull makes it finish quite quickly.
If there's any information or test that I can do that would help resolve this, just let me know.  I can reproduce it 100% of the time......

**Comment by JaviCerveraIngram** [comment] 2021-05-11 07:29
> This solves the issue:
> https://github.com/francescoinfante/dugite/pull/1/files
> Unsure yet why, anyone has an idea?

I see that this PR has gone ignored. Is this going to be merged?

**Comment by francescoinfante** [comment] 2021-05-11 07:39
> > This solves the issue:
> > https://github.com/francescoinfante/dugite/pull/1/files
> > Unsure yet why, anyone has an idea?
> 
> I see that this PR has gone ignored. Is this going to be merged?

Unfortunately, I don't have the time to understand why the fix works and to make a PR to the original repo.

What I can tell is that I was managing to replicate it 100% of the times and, with that fix, I'm using github desktop daily on my main machine without issues.

**Comment by shiftkey** [comment] 2021-05-25 20:33
I've published a new build with what several folk believe is the fix for this issue - please try it out and let me know if it works for you [`2.8.1-linux3`](https://github.com/shiftkey/desktop/releases/tag/release-2.8.1-linux3).

**Comment by Jord-JD** [comment] 2021-05-25 21:26
@shiftkey I've done a few quick tests, and this seems to have fixed it! Many thanks.

**Comment by MrTruth0** [comment] 2021-05-25 22:14
@shiftkey Nice, it works, now i have the problem where after the Commit, when i click on the Push button, it will stay on "Hang On" until i switch the Window, i've tried with 3 commits, 2 in one Repo and 1 on another (Sorry for my bad eng)

**Comment by shiftkey** [comment] 2021-05-25 23:33
> now i have the problem where after the Commit, when i click on the Push button, it will stay on "Hang On" until i switch the Window, i've tried with 3 commits, 2 in one Repo and 1 on another (Sorry for my bad eng)

@MrTruth0 please open a fresh issue and fill out the bug report template - this is a different issue to the original one and it needs to be handled separately

**Comment by masseelch** [comment] 2021-05-26 05:28
Interestingly enough, for me it did **NOT** fix the issue. However, I did build the binary myself. Sources are of [commit 608b733](https://github.com/shiftkey/desktop/commit/608b733bf0cbdeafbeddbd9a3ef36ed71575fa48).

The new build also introduced a new bug: Switching branches now does not update the view until I force it to (by clicking somewhere or switching out of and into the app).

**Comment by BudgieInWA** [comment] 2021-05-26 06:28
Fixes the problem for me (Ubuntu 20.04.2).

**Comment by krushnaj** [comment] 2021-05-26 07:06
@shiftkey Fixes the problem. Working smoothly like it was before.

**Comment by lozitskiys** [comment] 2021-05-26 09:00
I updated to 2.8.1-linux3 and commit freeze is finally fixed! But now pull origin does not update the view until i click somewhere...

**Comment by shiftkey** [comment] 2021-05-26 10:55
> The new build also introduced a new bug: Switching branches now does not update the view until I force it to (by clicking somewhere or switching out of and into the app).

@masseelch if you'd like me to investigate this, please open a new bug report and provide as much detail as possible.

**Comment by orrinoAriel** [comment] 2021-05-26 12:20
after merged this--->https://github.com/shiftkey/desktop/pull/506
This issue is still happening, but, in my case, when I try to do a pull...

**Comment by shiftkey** [comment] 2021-05-26 12:23
> This issue is still happening, but, in my case, when I try to do a pull...

@orrinoAriel I consider this a different test case that I'd like to investigate - please open a new issue unless you see an existing open issue that matches your behaviour

**Comment by canvural** [comment] 2021-05-26 12:29
I can confirm with https://github.com/shiftkey/desktop/releases/tag/release-2.8.1-linux3 I no longer have the commit freeze issue. Thank you @shiftkey 👍🏽

**Comment by masseelch** [comment] 2021-05-26 14:31
> > The new build also introduced a new bug: Switching branches now does not update the view until I force it to (by clicking somewhere or switching out of and into the app).
> 
> @masseelch if you'd like me to investigate this, please open a new bug report and provide as much detail as possible.

I went through my logs and the build I did failed due to loss of network while fetching yarn dependencies :facepalm:. I did not see that (was with my dog while compilation) and afterwards just started the app. 

With a new and clean build I can confirm the issue gone. Sorry for the inconvenience.

**Comment by shiftkey** [comment] 2021-05-26 14:33
@masseelch no problem, thanks for validating the fix!

**Comment by shiftkey** [comment] 2021-05-27 11:57
I've seen enough 👍🏻 or comments confirming the fix that I'm happy to close this out.

For other actions spotted that seems similar to this original issue, please check the list of open issues in the project (or add a new issue if your problem doesn't seem to be listed) if you would like me to investigate further.

**Closed as completed by shiftkey** 2021-05-27 11:57 UTC
Labels: help wanted, bug

**Comment by kvz** [comment] 2021-05-27 14:07
Working well! It's my daily bread so this is going to make my days so much better, thanks all! :1st_place_medal:

**Comment by Akkadius** [comment] 2021-05-29 20:29
This fix works great, however pushing the commits seem to suffer from the same issue on https://github.com/shiftkey/desktop/releases/tag/release-2.8.1-linux3

I have to tab away and back in order for it to show pushed

**Comment by otseng** [comment] 2021-08-21 19:19
> I've published a new build with what several folk believe is the fix for this issue - please try it out and let me know if it works for you [`2.8.1-linux3`](https://github.com/shiftkey/desktop/releases/tag/release-2.8.1-linux3).

Works for me on Ubuntu 20.04.  Thanks.
