### ISSUE TITLE
/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy

### ISSUE THREAD

**Issue by Alessio-Rigoli** [shiftkey/desktop#192] opened 2019-12-22 23:13 UTC
### Describe the feature or problem you’d like to solve
Good morning how are going,
I recently installed the GitHub desktop application via SNAP and recieved the following error when trying to launch the application and was wondering if this was a known bug or a solution exists.
Thanks

**Comment by immackay** [comment] 2019-12-29 05:11
Hi there, gonna point you towards #163 - there's instructions for downgrading the snap there, alternatively you can install the .deb

**Comment by Alessio-Rigoli** [comment] 2019-12-29 06:48
Thank you, I'll give that a try.

**Comment by shiftkey** [comment] 2020-02-07 19:05
Closing this out as a duplicate of #163

**Closed as completed by shiftkey** 2020-02-07 19:05 UTC
Labels: installers/snap
