### ISSUE TITLE
Snap fails to start

### ISSUE THREAD

**Issue by ziggy42** [shiftkey/desktop#145] opened 2019-05-01 10:32 UTC
## Description
I installed the snap with:
```bash
sudo snap install github-desktop --beta --classic
```
and run it:
```bash
➜  ~ github-desktop                            

(github-desktop:7273): Gtk-WARNING **: 12:29:11.933: cannot open display: :0
```
and the app doesn't start.

## Version
* Operating system: Fedora 30, GNOME 3.32 running on Wayland

**Comment by shiftkey** [comment] 2019-05-01 10:56
Possibly thee same root cause as #142 (how the Snap is being built is incompatible with newer distros).

Keep an eye on #144

**Comment by ziggy42** [comment] 2019-05-03 09:58
Same happens on Fedora 29
```
➜  ~ snap run github-desktop
/snap/github-desktop/59/usr/sbin/update-icon-caches: line 16: gtk-update-icon-cache-3.0: command not found
WARNING: icon cache generation failed for /home/andrea/snap/github-desktop/59/.local/share/icons/hicolor
/snap/github-desktop/59/usr/sbin/update-icon-caches: line 16: gtk-update-icon-cache-3.0: command not found
WARNING: icon cache generation failed for /home/andrea/snap/github-desktop/59/.local/share/icons/default

(github-desktop:15253): Gtk-WARNING **: 11:58:10.488: cannot open display: :0
```

**Comment by shiftkey** [comment] 2019-05-12 13:33
@ziggy42 if you run `snap run --strace github-desktop` do you see anything interesting? I'm honestly not sure why `gtk-update-icon-cache-3.0` is being called like this, but I hope #144 will also close this out.

**Comment by ziggy42** [comment] 2019-05-12 14:11
I'm not familiar with `strace` so I'm not sure the following is something related to github-desktop or strace itself :smile: 
```
➜  ~ snap run --strace github-desktop
error: cannot find an installed strace, please try 'snap install strace-static'
➜  ~ snap install strace-static
strace-static 4.20 from Canonical✓ installed
➜  ~ snap run --strace github-desktop
/var/lib/snapd/snap/strace-static/current/bin/strace: Unexpected wait status 0x8b
error: exit status 1
```

**Comment by shiftkey** [comment] 2019-05-12 14:40
@ziggy42 no problem, happy to leave it until after I wrap up #144

**Comment by shiftkey** [comment] 2020-04-04 21:06
I'm going to close this out for now to keep the issue tracker under control, as I am unable to package Snaps locally to revisit issues with Snaps like this one. Please follow along with #203 in the meantime.

**Closed as completed by shiftkey** 2020-04-04 21:06 UTC
Labels: unclear, installers/snap
