### ISSUE TITLE
Can't maximize the window in Debian 9.4

### ISSUE THREAD

**Issue by vdegenne** [shiftkey/desktop#35] opened 2018-04-02 02:03 UTC
A picture always self explanatory

<img src="http://vdegenne.com/img/Screenshot%20from%202018-04-02%2003-50-45.png" />

It is a fresh installation of Debian, and a fresh installation of the last release (1.1.1) of GitHub Desktop for Linux.

**Comment by Serkan-devel** [comment] 2018-04-02 12:41
I can maximize the window on Debian 9.4 lxqt. Maybe it's an issue with gnome again

![auswahl_045](https://user-images.githubusercontent.com/16866642/38196514-d75378cc-3683-11e8-8722-7dc9f683d1f4.png)

**Comment by vdegenne** [comment] 2018-04-02 19:49
@shiftkey why the unclear label ? I just reported a problem. I can't maximize the window. If you check the screenshot, the "maximize" option in the context menu is grey and can't be clicked.
I usually like my windows to take all the available space on my desktop (just like everyone else I guess), but sadly couldn't make that happen. I also pointed out the fact I tried to run the app on a fresh install of **Debian 9.4** and I didn't modify the app before running or anything.

**Comment by vdegenne** [comment] 2018-04-02 19:55
@Serkan-devel I should probably give lxqt a try, it looks nice and at least GitHub Desktop will work there.. GitHub Desktop is using Electron I guess, so I think nobody on this repository will be able to fix that issue as it seems to be about the container more than the containee. Thanks to point that out.

**Comment by Serkan-devel** [comment] 2018-04-02 21:26
Maybe it's an electron issue within gnome. I use a somewhat fresh installation of Debian 9.1 updated to 9.4. I don't experience any problems on lxqt, except you need to change `pavucontrol` to `pavucontrol-qt` in the sound settings if you see it, but I can also recommend xfce or kde. Kde seems to have become more stable and lightweight lately

**Comment by shiftkey** [comment] 2018-04-02 23:18
@vdegenne I'm using the `unclear` label to flag issues that need investigation. I also don't have a Debian VM currently to test, so it's a way to for me to signal that I need help digging into it.

**Comment by shiftkey** [comment] 2018-04-02 23:25
@vdegenne one thing to try out - what if you install the [`1.1.0`](https://github.com/shiftkey/desktop/releases/tag/release-1.1.0) build instead? There was a change in the Electron version (1.7.11 to 1.8.3) between these two builds, and if the older version does work as expected that gives us more insight into what might have regressed for your setup.

**Comment by Serkan-devel** [comment] 2018-04-02 23:46
@shiftkey where can one get the logs for electron apps?

**Comment by shiftkey** [comment] 2018-08-12 14:59
@Serkan-devel apologies for missing this:

> where can one get the logs for electron apps?

These should be found at `~/.config/GitHub Desktop/logs/`.

**Comment by shiftkey** [comment] 2018-11-20 18:41
I'm going to close this out because I never did get a screenshot or more details about the issue. It was reported against Electron `1.8.3` and we're now using Electron `2.0.13`, so a lot has changed here and this has been the only report of it.

@vdegenne please open a new issue with details to reproduce the issue if you're still able to encounter it.

**Closed by shiftkey** 2018-11-20 18:41 UTC
Labels: unclear
