### ISSUE TITLE
Speed up the push or pull

### ISSUE THREAD

**Issue by leogitpro** [shiftkey/desktop#493] opened 2021-05-06 03:24 UTC
As the same networking. Windows and Ubuntu, same repo, same account.
Github Desktop (Official version) on Windows when pull and push repos very fast.
Github Desktop (Linux version: AppImage/deb) on Linux very slowly for push or pull repos. every action hand on ... many minutes.

Is the Linux version wait for what? hand on ... waiting for ages. Is any way or config speed up that?
Thanks very much.

**Comment by K0-RR** [comment] 2021-05-06 08:12
Probably a duplicate of #329.

**Comment by shiftkey** [comment] 2021-05-06 17:43
@leogitpro without more information from the log files (accesible from the **Help** menu) or details about recreating the issue on my end there's not much I can do here.

I think you might be encountering the same thing as #329 but I've not sure how push/pull are related to what I suspect is the root cause here (sending stdin to Git processes).

**Comment by leogitpro** [comment] 2021-05-07 06:46
> @leogitpro without more information from the log files (accesible from the **Help** menu) or details about recreating the issue on my end there's not much I can do here.
> 
> I think you might be encountering the same thing as #329 but I've not sure how push/pull are related to what I suspect is the root cause here (sending stdin to Git processes).

Sorry, there is a duplicate issue report. Thanks @RDKRACZ . Please close the issue.

**Closed as completed** 2021-05-07 21:12 UTC
Labels: unclear
