### ISSUE TITLE
Error: user interaction failed

### ISSUE THREAD

**Issue by lillelilje** [shiftkey/desktop#621] opened 2021-11-03 16:49 UTC
### Describe the bug
When trying to sign in to account I get the error "Error: user interaction failed"

### Version & OS

Version 2.9.4-linux1 (x64)

Fedora 35

**Flatpak** version

### Steps to reproduce the behavior

1. Go to File
2. Click on Options
3. Click on Sign In

### Expected behavior

Successfully logging in

### Actual behavior

Clicking Sign In leads to a github page where I must accept. After accepting the client shows the error.

### Screenshots

![image](https://user-images.githubusercontent.com/1491401/140105379-21e8ee59-504d-4c4a-9efb-ab1b1a8485aa.png)

### Logs

```
2021-11-03T16:38:06.443Z - info: [ui] [AppStore] loading 0 repositories from store
2021-11-03T16:38:06.459Z - info: [ui] [Welcome] no sign in step found. ignoring...
2021-11-03T16:38:06.461Z - info: [ui] [Welcome] no sign in step found. ignoring...
2021-11-03T16:38:06.513Z - info: [ui] [Welcome] no sign in step found. ignoring...
2021-11-03T16:38:06.516Z - info: [ui] launching: 2.9.4-linux1 (Linux 5.14.14-300.fc35.x86_64)
2021-11-03T16:38:06.517Z - info: [ui] execPath: '/app/github-desktop/github-desktop'
2021-11-03T16:38:06.545Z - info: [ui] [Welcome] no sign in step found. ignoring...
2021-11-03T16:38:06.832Z - info: [ui] Opt in reported.
2021-11-03T16:38:08.533Z - info: [ui] [Welcome] advancing to step: SignInToDotComWithBrowser
2021-11-03T16:38:08.533Z - info: [ui] [SignInStore] initializing OAuth flow
2021-11-03T16:38:08.536Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=4e58a7b8-1af8-4422-8074-ef529acd7dbd
2021-11-03T16:38:08.537Z - info: [ui] [Welcome] current sign in state not found. ignoring...
2021-11-03T16:38:08.630Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2021-11-03T16:39:09.519Z - info: [main] Received possible protocol arguments: 2
2021-11-03T16:39:09.519Z - info: [main] Processing protocol url
2021-11-03T16:39:09.528Z - info: [ui] [Dispatcher] requesting authenticated user
2021-11-03T16:39:09.532Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2021-11-03T16:39:09.536Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...
2021-11-03T16:39:10.277Z - info: [ui] [SignInStore] account resolved
2021-11-03T16:39:10.277Z - info: [ui] [AppStore] adding account fosspill (fosspill) to store
2021-11-03T16:39:10.279Z - info: [ui] [Welcome] advancing to step: ConfigureGit
2021-11-03T16:39:10.316Z - error: [ui] Error adding account 'fosspill'
Error: user interaction failed
2021-11-03T16:39:10.321Z - info: [ui] [Welcome] no sign in step found. ignoring...
2021-11-03T16:40:37.662Z - info: [ui] [SignInStore] initializing OAuth flow
2021-11-03T16:40:37.664Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=2a5e2fb9-c07c-41b5-9b88-8a65891e115b
2021-11-03T16:40:38.736Z - info: [main] Received possible protocol arguments: 2
2021-11-03T16:40:38.736Z - info: [main] Processing protocol url
2021-11-03T16:40:38.737Z - info: [ui] [Dispatcher] requesting authenticated user
2021-11-03T16:40:39.404Z - info: [ui] [SignInStore] account resolved
2021-11-03T16:40:39.404Z - info: [ui] [AppStore] adding account fosspill (fosspill) to store
2021-11-03T16:40:39.411Z - error: [ui] Error adding account 'fosspill'
Error: user interaction failed
2021-11-03T16:40:46.945Z - info: [ui] [SignInStore] initializing OAuth flow
2021-11-03T16:40:46.956Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=f2ad58a2-97c0-4367-923f-3e18aa054738
2021-11-03T16:40:47.915Z - info: [main] Received possible protocol arguments: 2
2021-11-03T16:40:47.916Z - info: [main] Processing protocol url
2021-11-03T16:40:47.917Z - info: [ui] [Dispatcher] requesting authenticated user
2021-11-03T16:40:48.525Z - info: [ui] [SignInStore] account resolved
2021-11-03T16:40:48.525Z - info: [ui] [AppStore] adding account fosspill (fosspill) to store
2021-11-03T16:40:48.532Z - error: [ui] Error adding account 'fosspill'
Error: user interaction failed
2021-11-03T16:41:47.290Z - info: [ui] [AppStore] loading 0 repositories from store
2021-11-03T16:41:47.351Z - info: [ui] launching: 2.9.4-linux1 (Linux 5.14.14-300.fc35.x86_64)
2021-11-03T16:41:47.351Z - info: [ui] execPath: '/app/github-desktop/github-desktop'
2021-11-03T16:41:47.737Z - info: [ui] Stats reported.
2021-11-03T16:41:54.094Z - info: [ui] [SignInStore] initializing OAuth flow
2021-11-03T16:41:54.097Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=808964b0-3b1e-442c-bee8-8cd215376d46
2021-11-03T16:41:55.070Z - info: [main] Received possible protocol arguments: 2
2021-11-03T16:41:55.070Z - info: [main] Processing protocol url
2021-11-03T16:41:55.071Z - info: [ui] [Dispatcher] requesting authenticated user
2021-11-03T16:41:55.789Z - info: [ui] [SignInStore] account resolved
2021-11-03T16:41:55.789Z - info: [ui] [AppStore] adding account fosspill (fosspill) to store
2021-11-03T16:41:55.797Z - error: [ui] Error adding account 'fosspill'
Error: user interaction failed
2021-11-03T16:42:33.988Z - info: [ui] [SignInStore] initializing OAuth flow
2021-11-03T16:42:33.996Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=4e8e5148-4c64-4cc6-95f9-4f7b244f9108
2021-11-03T16:42:34.999Z - info: [main] Received possible protocol arguments: 2
2021-11-03T16:42:34.999Z - info: [main] Processing protocol url
2021-11-03T16:42:34.999Z - info: [ui] [Dispatcher] requesting authenticated user
2021-11-03T16:42:35.583Z - info: [ui] [SignInStore] account resolved
2021-11-03T16:42:35.583Z - info: [ui] [AppStore] adding account fosspill (fosspill) to store
2021-11-03T16:42:35.595Z - error: [ui] Error adding account 'fosspill'
Error: user interaction failed
2021-11-03T16:42:50.554Z - info: [ui] [SignInStore] initializing OAuth flow
2021-11-03T16:42:50.562Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=afa1ee93-5f02-4727-81a4-5fe6fa7cddae
2021-11-03T16:42:51.466Z - info: [main] Received possible protocol arguments: 2
2021-11-03T16:42:51.466Z - info: [main] Processing protocol url
2021-11-03T16:42:51.467Z - info: [ui] [Dispatcher] requesting authenticated user
2021-11-03T16:42:52.061Z - info: [ui] [SignInStore] account resolved
2021-11-03T16:42:52.061Z - info: [ui] [AppStore] adding account fosspill (fosspill) to store
2021-11-03T16:42:52.067Z - error: [ui] Error adding account 'fosspill'
Error: user interaction failed
2021-11-03T16:47:26.108Z - info: [ui] [SignInStore] initializing OAuth flow
2021-11-03T16:47:26.117Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=cecb0657-5350-4791-9f61-38d94d219d98
2021-11-03T16:47:27.134Z - info: [main] Received possible protocol arguments: 2
2021-11-03T16:47:27.134Z - info: [main] Processing protocol url
2021-11-03T16:47:27.135Z - info: [ui] [Dispatcher] requesting authenticated user
2021-11-03T16:47:27.884Z - info: [ui] [SignInStore] account resolved
2021-11-03T16:47:27.885Z - info: [ui] [AppStore] adding account fosspill (fosspill) to store
2021-11-03T16:47:27.892Z - error: [ui] Error adding account 'fosspill'
Error: user interaction failed
```

**Comment by NuSynth** [comment] 2021-12-08 11:21
I'm having the same issue using the flatpak in KDE, but it works fine in Gnome for me. The AppImage works fine for either system for me though.

**Comment by shiftkey** [comment] 2021-12-18 19:15
I'd recommend reaching out to the Flatpak-specific issue tracker as I'm not sure what might be the issue here: https://github.com/flathub/io.github.shiftey.Desktop

I'm not getting much clues about the `Error: user interaction failed` message here aside from that it's occurring while the app is trying to store the credential using `libsecret`, so perhaps there's something related to `gnome-keyring` (or using this on a KDE distribution) that's the root cause here...

**Comment by shiftkey** [comment] 2022-04-03 19:05
Closing this out for now as I don't have a good resolution for this issue...

**Closed as completed by shiftkey** 2022-04-03 19:05 UTC
Labels: installers/flatpak, dbus
