### ISSUE TITLE
Can't log into github desktop

### ISSUE THREAD

**Issue by mei1212123** [shiftkey/desktop#666] opened 2022-02-26 05:32 UTC
### Describe the bug
When logging into GitHub desktop the application hangs 

### Version & OS
2.9.9-linux2 (github-desktop-bin on the aur) 
Arch Linux (fresh install)

### What I've tried
2 browsers (firefox and brave) 
Reinstalling the program
adding:
```
source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh &
eval $(/usr/bin/gnome-keyring-daemon --start) &
export SSH_AUTH_SOCK &
```
assuming it was a keyring issue (which it wasnt)

### Images of what happened
![retard](https://user-images.githubusercontent.com/71238085/155830567-fdf85a3b-6cff-4628-b456-3f4a50c1fb72.png)
![unknown](https://user-images.githubusercontent.com/71238085/155830593-44793061-6592-41b2-ba2f-c6ff16fc2711.png)

**Comment by yasanglass** [comment] 2022-02-26 08:22
I have the same issue with Fedora 35. Tried both RPM & Flatpak. This is a fresh Fedora install but I didn't have this issue a month ago on the same system and os.

Not sure what exactly you meant by "hangs" but my app is responsive. But just gets stuck in the state of waiting for the login. It never ends but I can easily cancel it.

**Comment by VanderlyBelo** [comment] 2022-02-26 15:23
I'm going thru the same issue too. The application gets stuck, always waiting for the login, just after the authorization and redirection by the browser. It's possible to cancel, but the process of syncing never ends. Here are my pieces of information so far: 
*  **Os System and versions:**
Github Desktop 2.9.9-linux2 
Ubuntu 20.04.4 LTS

* **What I've tried so far:**
Installation by line code (2.9.6) 
Download and install Deb packages (.deb) direct from Github Shiftkey profile (I've tried several versions from 2.9.6 until 2.9.9 yet, and counting.)(uninstall and reinstall)
Changing default browsers (I've tried Chrome, Firefox, and Chromium)

* **Images:**

![Screenshot from 2022-02-26 12-00-45](https://user-images.githubusercontent.com/100372303/155847907-f02159ff-83a4-4f86-a62d-695b56d68cd3.png)

* **It is working now!**

After the attempts described before, I only typed some commands such as auto-remove, update, and upgrade before turning the system off, and when I turned it on again, the application was working perfectly. I did not realize what exactly happened but now, the application is working smoothly. The last installation was made by the command line.

![Screenshot from 2022-02-26 16-06-55](https://user-images.githubusercontent.com/100372303/155856034-71744e38-d7e0-49c6-b97b-b308f87d9b44.png)
![Screenshot from 2022-02-26 16-21-46](https://user-images.githubusercontent.com/100372303/155856361-db48229f-d2d4-4271-bad6-3dec2caa8c5c.png)

I hope this can help somehow. Thanks!

**Comment by Alessandro-filho** [comment] 2022-02-27 00:58
I had the same problem and the solution was to have version [2.6.6](https://github.com/shiftkey/desktop/releases/tag/release-2.6.6-linux1) installed and from that I was able to log in, then just go to the synapics package manager and run update, then go to [2.9.6](https://github.com/shiftkey/desktop/releases/tag/release-2.9.6-linux1) already logged in.

**Comment by osbm** [comment] 2022-02-27 11:44
I have a manjaro system(installed today).
I tried both github-desktop and github-desktop-git on AUR. Both does not work it just stays in this 
![image](https://user-images.githubusercontent.com/74963545/155880962-90bd4bc6-0c09-4203-8208-1601e1b5224c.png)
pop up. I tried firefox and chrome.

 It opens a link and that link tries to open immediately with github-desktop app. The browser page doesn't even open.

**Comment by lidarbtc** [comment] 2022-03-01 08:44
@VanderlyBelo 
delete 2.9.9 
install 2.9.6 and it's work!
very thanks you
thank you for your help

**Comment by mwt** [comment] 2022-03-01 13:06
Note: These reports are mostly about Arch Linux. This is probably just because 2.9.9 is in the AUR but is not yet in the deb/rpm repos.

**Update:** Yes. Definitely not an Arch-specific issue.

**Comment by liaoliaots** [comment] 2022-03-03 10:44
@VanderlyBelo thanks, version 2.9.6 works fine.

**Comment by navalex** [comment] 2022-03-03 12:45
Also have the same issue. I'm running the app on Kubuntu 20.04, my Github-Desktop app is on v2.9.9, tried with both Chrome and Firefox, the app just hang infinitely. Didn't found any workaround.

**Comment by andersenthomas** [comment] 2022-03-04 09:56
Can't seem to get this working on my Ubuntu 20.04 even with v2.9.6 AppImage. Gettting an "Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached" error message. Using FireFox by the way.

**Comment by whitetechnologies** [comment] 2022-03-04 17:14
Same issue with Ubuntu 20.04 on v.2.9.9. Please fix : ) 

UPDATE: Using 2.9.6 works fine

Was using .deb in both cases

**Comment by tom-ricci** [comment] 2022-03-06 05:28
Same issue on Ubuntu 21.09 and v2.2.9

**Comment by JamesMcCullochDickens** [comment] 2022-03-06 21:52
@tom-ricci did you find a fix for this problem for Ubuntu?

**Comment by tom-ricci** [comment] 2022-03-06 22:03
> @tom-ricci did you find a fix for this problem for Ubuntu?

I just downgraded to v2.9.6 for now.

**Comment by thaisfds** [comment] 2022-03-07 18:07
> > @tom-ricci did you find a fix for this problem for Ubuntu?
> 
> I just downgraded to v2.9.6 for now.

I changed the version to 2.9.6 but I still have the same problem. Ubuntu 20.04.4 LTS.

**Comment by taciturnaxolotl** [comment] 2022-03-08 17:58
Have this error noticed this in the logs: ```2022-03-08T17:54:01.677Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--enable-crashpad"}```  
The full logs:   
```  
2022-03-08T17:52:11.775Z - info: [ui] [Welcome] current sign in state not found. ignoring...  
2022-03-08T17:52:11.910Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...  
2022-03-08T17:52:13.717Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...  
2022-03-08T17:52:13.726Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...  
2022-03-08T17:52:15.510Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...  
2022-03-08T17:52:44.909Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...  
2022-03-08T17:52:45.326Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...  
2022-03-08T17:54:01.666Z - info: [main] Received possible protocol arguments: 4  
2022-03-08T17:54:01.666Z - info: [main] Processing protocol url  
2022-03-08T17:54:01.677Z - warn: [ui] Unknown URL action: unknown - payload: {"name":"unknown","url":"--enable-crashpad"}  
2022-03-08T17:54:01.678Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...  
2022-03-08T17:54:01.690Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...  
2022-03-08T17:54:03.839Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...  
2022-03-08T17:54:04.239Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...  
2022-03-08T17:54:04.255Z - info: [ui] [Welcome] kind Authentication is the same as Authentication. ignoring...```
I used the latest deb release and am on Pop OS 21.10 also tested on appimage release.

**Comment by jnv** [comment] 2022-03-10 09:33
For Flatpak users, you can downgrade to 2.9.6 on [this commit](https://github.com/flathub/io.github.shiftey.Desktop/commit/42ca1398dad841a2cf05b63d11cde276fa21b169):

```shell
sudo flatpak update --commit=cfe12885e04a5e10a911f51847c194391479ba7e8389f1ffcce63bfc26eb910e io.github.shiftey.Desktop
```

(Mind that the commit used by the flatpak is different from the repository, see [instructions on downgrading](https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks#downgrading)).

Once I finished the authentication and updated to 2.9.9, it still works.

**Comment by navalex** [comment] 2022-03-11 11:57
Finally, i fixed the issue.
I installed github-desktop using the .deb package of the release. So i just did `sudo apt remove --purge github-desktop`
Then i followed the install guide for Ubuntu/Debian user to add the source to apt, then i installed it with `sudo apt install github-desktop`
And it worked ;)

**Comment by mwt** [comment] 2022-03-11 13:12
> then i installed it with `sudo apt install github-desktop`
> And it worked ;)

Great! This is the same as downgrading because the apt repo is still on 2.9.6.

**Comment by taciturnaxolotl** [comment] 2022-03-11 13:22
Worked for me to thanks!

**Comment by navalex** [comment] 2022-03-11 13:28
> > then i installed it with `sudo apt install github-desktop`
> > And it worked ;)
> 
> Great! This is the same as downgrading because the apt repo is still on 2.9.6.

Yeah true ^^ didn't checked the version difference.

**Comment by tom-ricci** [comment] 2022-03-11 15:22
Given the fact that this issue has been around for almost two weeks now and other issues about this are popping up, should someone downgrade this to 2.9.6 on each package manager (or at least add a disclaimer in the readme or release notes)?

**Comment by mwt** [comment] 2022-03-11 15:30
> should someone downgrade this to 2.9.6 on each package manager

I think the affected ones are Flatpak, AUR, and AppImage.

**Comment by khaneliman** [comment] 2022-03-11 16:50
I modified the PKGBUILD from the aur to build and install 2.9.6 to log in, then reinstalled 2.9.9. 

If you're using yay, `~/.cache/yay/github-desktop` change `pkgver=2.9.9` to `pkgver=2.9.6` and `_gitname="release-$pkgver-linux2"` to `_gitname="release-$pkgver-linux1"`.

I also changed the makedependency from nodejs-gallium to nodejs so that it didn't have to deal with that conflict.

**Comment by CatWithCode** [comment] 2022-03-13 11:18
Manjaro Linux (Arch). Can not log in v2.9.9. But 2.9.6 works!

**Comment by TogoFire** [comment] 2022-03-14 00:24
I tried all the solutions commented here. Nothing works.

**Comment by tom-ricci** [comment] 2022-03-14 01:16
@TogoFire What's your system info, logs, etc? Maybe there's something weird going on that 2.9.9 made more common instead of just a random regression someone didn't notice.

**Comment by ng0177** [comment] 2022-03-18 11:00
Same issue here.
```
Description:	EndeavourOS Linux
5.16.14-arch1-1

2 aur/github-desktop-bin 2.9.9-2 (+36 1.09) (Installed)
    GUI for managing Git and GitHub.
```

**Comment by compieter-gh** [comment] 2022-03-20 14:59
> For Flatpak users, you can downgrade to 2.9.6 on [this commit](https://github.com/flathub/io.github.shiftey.Desktop/commit/42ca1398dad841a2cf05b63d11cde276fa21b169):
> 
> ```shell
> sudo flatpak update --commit=cfe12885e04a5e10a911f51847c194391479ba7e8389f1ffcce63bfc26eb910e io.github.shiftey.Desktop
> ```
> 
> (Mind that the commit used by the flatpak is different from the repository, see [instructions on downgrading](https://github.com/flatpak/flatpak/wiki/Tips-&-Tricks#downgrading)).
> 
> Once I finished the authentication and updated to 2.9.9, it still works.

Thank youu!

**Comment by shiftkey** [comment] 2022-04-03 16:14
Apologies for the delay in digging into this - I've had many other things distracting me. I recommend downgrading in the meantime to an earlier version, as those should be unaffected.

I've dusted off my test machine and walked through the steps here and I see this `--enable-breakpad` message when I do the sign-in flow, so clearly something's broken here with how the app is being re-launched with the `2.9.9` update.

**Comment by shiftkey** [comment] 2022-04-03 17:22
I've backported the bugfix from #687 to the release where this was first noticed, if you want to verify this addresses:

 - [`2.9.9 Linux RC3`](https://github.com/shiftkey/desktop/releases/tag/release-2.9.9-linux3)

Otherwise this is available in the latest release that contains all the upstream changes:

 - [`2.9.12 Linux RC2`](https://github.com/shiftkey/desktop/releases/tag/release-2.9.12-linux2)

I'll leave this open for a while to confirm this has resolved the problem for users, but if you're seeing different behaviour let's move this to a fresh issue due to the noise.

**Comment by shiftkey** [comment] 2022-04-03 19:18
[`2.9.12 Linux RC3`](https://github.com/shiftkey/desktop/releases/tag/release-2.9.12-linux3) is available for testing which has an additional fix

**Comment by shiftkey** [comment] 2022-04-03 20:56
Based on reports with #677 I suspect this latest build also resolves the issues reported here.

Will leave this open for a day or so, please let me know if that latest build works for you.

**Comment by CaroWall** [comment] 2022-04-07 17:44
I first installed 2.9.12 today (didn't know about this issue) and could not sign in:/. After downgrading to 2.9.6, it worked.
I'm on ubuntu 20.04

**Comment by shiftkey** [comment] 2022-04-08 14:11
> I first installed 2.9.12 today (didn't know about this issue) and could not sign in:/. 

@CaroWall which exact build are you using? `2.9.12-linux2` doesn't work, but `2.9.12-linux3` or later has the right fix.

Otherwise please open a fresh issue with details about your setup as I haven't heard anyone else encountering issues with this latest build.

**Closed as completed by shiftkey** 2022-04-08 14:11 UTC
Labels: retest-requested
