### ISSUE TITLE
No menu icon after updating to 2.8.3-linux1.

### ISSUE THREAD

**Issue by K0-RR** [shiftkey/desktop#522] opened 2021-06-08 21:28 UTC
Installed the latest deb and now I can only launch it from the terminal.

OS: Ubuntu Cinnamon 21.04 x86_64
Kernel: 5.11.0-18-generic

**Comment by shiftkey** [comment] 2021-06-08 21:36
Could there be something wrong/deprecated with the `.desktop` file we include in the installer that's now removed in Cinnamon and causing it to not be detected by the OS?

**Comment by K0-RR** [comment] 2021-06-08 21:55
As I skipped a few versions I downgraded to 2.8.1 Linux RC3 to check this properly and the icon was there again, then I updated to 2.8.2 Linux RC1 and the icon is no more so probably something is wrong beginning from this version.

**Comment by K0-RR** [comment] 2021-07-12 20:45
I'm now on 2.9.0 Linux RC2 and the menu icon is back again. Were there any changes that could have fixed this?

Edit. now on 2.9.0 Linux RC3 and again no menu entry, I really don't know what is happening.

**Comment by K0-RR** [comment] 2021-07-15 22:51
It now also doesn't have an icon
![image](https://user-images.githubusercontent.com/43277609/125867606-bfbe15ab-6b8e-4995-b34b-cf1d1040c850.png)

**Comment by shiftkey** [comment] 2021-07-19 12:21
Only thing that's changed with [`2.9.0-linux3`](https://github.com/shiftkey/desktop/releases/tag/release-2.9.0-linux3) is the icons were updated in #530 to match the new theme, which I thought would fix a different bug. No changes to path names, just the contents of the images.

**Comment by shiftkey** [comment] 2021-07-19 12:22
Actually, there was one other change that may be the root cause of this recent regression. I removed this line which was setting the icon at the app window level:

```ts
windowOptions.icon = path.join(__dirname, 'static', 'icon-logo.png')
```

Perhaps I need to put that back, as it turns out this was used by the app at runtime.

**Comment by shiftkey** [comment] 2021-07-19 14:20
Please test [`2.9.0-linux4`](https://github.com/shiftkey/desktop/releases/tag/release-2.9.0-linux4) to see if that resolves this latest issue.

I'm still stumped a bit about why the menu icon isn't working in Cinnamon, but I'm also not familiar with how Cinnamon changes things for Ubuntu...

**Comment by K0-RR** [comment] 2021-07-19 14:40
This release resolves **both** issues, yeah I don't know what is going on.
I will create a virtual machines with cinnamon (Mint and Ubuntu) to test this again but since the Github menu icon is the only one that disappears and appears randomly when updating I doubt it's something with my system.

Also, this gets printed when launching from a terminal but you probably know about it
`(node:2389692) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information`

**Comment by shiftkey** [comment] 2021-07-19 14:52
@RDKRACZ thanks for confirming. Happy to close this out and reopen it if you can spot what might have caused it.

That `contextIsolation` message is a warning about an upcoming Electron change. I see it locally too, might be able to mute it but we'll see if it breaks the app and needs more work before Electron 12 is adopted upstream.

**Closed as completed by shiftkey** 2021-07-19 14:52 UTC
Labels: installers/deb, retest-requested, needs-investigation

**Comment by K0-RR** [comment] 2021-07-20 23:52
>I will create virtual machines with cinnamon (Mint and Ubuntu) to test this again...

Not able to reproduce on a virtual machine, I know this issue is resolved but I'm so confused why this was happening.
Additionally I created a Linux Mint Xfce machine to test #559 with 2.9.0-linux4 and can confirm there is no icon on the taskbar.
