### ISSUE TITLE
blank white screen 

### ISSUE THREAD

**Issue by ramagj** [shiftkey/desktop#968] opened 2023-12-01 09:53 UTC
### The problem

github desktop is always on blank white screen, immediate after being launched

### Release version

3.3.5

### Operating system

Fedora Linux 38

### Steps to reproduce the behavior

Just launch the desktop client.
It's just the same even after reinstalling it

**Comment by shiftkey** [comment] 2023-12-01 19:13
Duplicate of https://github.com/shiftkey/desktop/issues/958, please re-test with the latest release https://github.com/shiftkey/desktop/releases/tag/release-3.3.5-linux2 (has to be installed manually for now) and see if it resolves for your setup.

**Closed as not planned by shiftkey** 2023-12-01 19:13 UTC
