### ISSUE TITLE
commit takes minutes not seconds

### ISSUE THREAD

**Issue by ng0177** [shiftkey/desktop#476] opened 2021-04-08 14:12 UTC
`Version 2.7.1-linux1` takes minutes not seconds for a commit even if a single character in respository consisting of just one file has changed. The command line only takes a fraction of a second.

**Comment by francescoinfante** [comment] 2021-04-08 17:09
Very likely, duplicate of https://github.com/shiftkey/desktop/issues/329

**Comment by shiftkey** [comment] 2021-04-17 16:59
Yep, this is the same thing as #329 there's some extra context in there about what I suspect is happening

**Closed as completed by shiftkey** 2021-04-17 16:59 UTC
