### ISSUE TITLE
Not able to sign-in

### ISSUE THREAD

**Issue by IbsanjU** [shiftkey/desktop#680] opened 2022-03-23 06:36 UTC
### Describe the bug
Iam not able to sign-in through the github desktop.
 

Iam using Endeavour Os

It will open the browser and comes back to GH Desktop but stays on loading state. Tried multiple times.

**Comment by K0-RR** [comment] 2022-03-23 09:43
Duplicate of #666 and #677. You didn't spare 3 seconds to look at the open issues before creating yours and ignored the template. You can temporarily downgrade to 2.9.6 to be able to sign it, then update to 2.9.9.

**Comment by IbsanjU** [comment] 2022-03-23 09:53
I have tried this with 3 different Linux distros and I faced the same issue over and over again. Pardon the template, I'm new to creating issues. However, most of the issues are still open regarding the Login issue.
I will try this quick fix to downgrading the app.

@RDKRACZ

**Closed as completed** 2022-03-23 09:53 UTC
