### ISSUE TITLE
Certificate not trusted (APT)

### ISSUE THREAD

**Issue by tct123** [shiftkey/desktop#1080] opened 2024-06-08 18:54 UTC
APT repository does not seem to work.

SH:
```sh
Fehl:6 https://apt.packages.shiftkey.dev/ubuntu any InRelease
  Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Fehler in der Verifizierung des Zertifikats. [IP: 2620:1ec:bdf::67 443]
```

**Comment by copystring** [comment] 2024-06-08 23:11
Same here. The certificate does not match https://apt.packages.shiftkey.dev instead it's for this wildcard domain *.azureedge.net

**Comment by error9900** [comment] 2024-06-09 19:37
I wonder if it's this happening again: https://github.com/shiftkey/desktop/issues/1044

**Comment by fetwar** [comment] 2024-06-10 04:46
+1 issue is also occurring for me running Ubuntu 23.10

This does seem quite similar to #1044, I personally can't see why the cause mentioned there would change the certificate name though and don't remember that happening when #1044 was occurring.

From memory #1044 resulted in a timeout

**Comment by HotoRas** [comment] 2024-06-11 11:54
On Debian 13, and I'm same here. mwt version is still avaliable to use, so I'd recommend to use that instead.

**Comment by QuentiumYT** [comment] 2024-07-02 14:39
Also the last version from this PPA is from March 31

```
Origin: apt.packages.shiftkey.dev
Label: apt.packages.shiftkey.dev
Codename: any
Date: Sun, 31 Mar 2024 17:55:28 UTC
Architectures: amd64
Components: main
Description: Package feed for GitHub Desktop on Linux packages
```

**Comment by shiftkey** [comment] 2024-07-13 19:49
Closing in favour of https://github.com/shiftkey/desktop/issues/1062

**Closed as not planned by shiftkey** 2024-07-13 19:49 UTC
