### ISSUE TITLE
Unknown or unsupported transport "disabled" for address "disabled:"

### ISSUE THREAD

**Issue by tellts** [shiftkey/desktop#225] opened 2020-03-07 06:11 UTC
Can't authenticate to GitHub
Unknown or unsupported transport "disabled" for address "disabled:"

This occurs when I click on a menu item:
Clone a repository from the internet ...
After that, I click on the text "Github.com" and then enter the login or email (I tried two options) and the password. Then I clicked on the "Sign in" button. 

### Version GitHubDesktop-linux-2.3.1-linux1.deb
![screenshot_1](https://user-images.githubusercontent.com/5172660/76137957-5f4b7c00-6064-11ea-9535-c8a001161c98.jpg)

Open 'About GitHub Desktop' menu to see the Desktop version. 
###In the menu about the program version is not written.
Also include what operating system you are using.
###AntiX.
I found a description of the solution to the problem "sudo apt install gnome-keyring" (https://github.com/desktop/desktop/issues/5678). It didn’t help me.
Writes:
The gnome-keyring package of the newest version (3.28.2-5) is already installed.

**Comment by tellts** [comment] 2020-03-07 16:44
I also tried clicking on the "Sign in using your browser" item. It opens a blank page on which there is no content and this does not help at all.

**Comment by shiftkey** [comment] 2020-03-08 15:25
> Unknown or unsupported transport "disabled" for address "disabled:"

This seems to be related to how the app tries to store and retrieve credentials. There's an upstream issue https://github.com/atom/node-keytar/issues/132 which explores getting error, and there were a couple of things in there to try.

It's not clear to me which distro you have setup, but maybe the daemon for `gnome-keyring` isn't running (which would explain the message being raised by `dbus`). Someone on that thread was able to get this working as part of a TravisCI build by running these two commands:

```
$ /usr/bin/gnome-keyring-daemon --login
$ /usr/bin/gnome-keyring-daemon --components=secrets --start
```

**Comment by shiftkey** [comment] 2020-03-08 15:25
> I also tried clicking on the "Sign in using your browser" item. It opens a blank page on which there is no content and this does not help at all.

Which browser is this launching?

**Comment by tellts** [comment] 2020-03-08 16:03
Hello. I am using the operating system antiX-19.1_x64-full.

I was advised to apply these commands, but it did not help.
```
export NO_AT_BRIDGE=1
eval $(dbus-launch --sh-syntax)
export DBUS_SESSION_BUS_PID
export DBUS_SESSION_BUS_WINDOWID
eval $(echo -n "" | /usr/bin/gnome-keyring-daemon --login)
eval $(/usr/bin/gnome-keyring-daemon --components=secrets --start)
```
These lines, if I understood correctly, are copied from the page
[(https://github.com/neo4j-apps/neo4j-desktop/issues/23)]

> Which browser is this launching?
Firefox.
It has already been launched. I don’t remember whether a new tab opens or if I opened it in advance and the request was substituted into the address bar.

**Comment by shiftkey** [comment] 2020-03-29 20:27
@tellts only other thing I can suggest at this stage is running `dbus-monitor` in the background to see if a helpful error appears that might explain why it's not working. This guide has some rules to help filter out the noise: https://wiki.ubuntu.com/DebuggingDBus

**Comment by jfgordon2** [comment] 2020-04-07 20:53
Might this be related to the dependency added in [PR 186](https://github.com/shiftkey/desktop/pull/186/files)? It seems unnecessary to explicitly call `gnome-keyring` if we already have `libsecret` unless the linux build is calling `gnome-keyring` and not just using it as a key store? - @tellts is there any chance you can test building locally?

**Comment by tellts** [comment] 2020-04-08 02:44
Hello. I don’t know yet.

**Comment by jfgordon2** [comment] 2020-04-08 02:51
@tellts some help getting this set up to build locally is [available here](https://github.com/shiftkey/desktop/blob/linux/docs/contributing/setup.md) if you’re feeling adventurous.

**Comment by shiftkey** [comment] 2020-04-08 11:04
@jfgordon2 the app doesn't call `gnome-keyring` directly, but it requires some sort of backend to handle it's requests to the Secret Service API (what `libsecret` represents).

We added `gnome-keyring` in that PR because it's convenient for GNOME users, and should run the necessary daemon that listens for these requests

**Comment by shiftkey** [comment] 2020-05-25 12:18
Closing this one out because I don't have any more information to understand this problem. 

@tellts if you do have time to reproduce this again the output from `dbus-monitor` from my earlier comment could help us understand what's happening on your machine https://github.com/shiftkey/desktop/issues/225#issuecomment-605695758

**Closed as completed by shiftkey** 2020-05-25 12:18 UTC
Labels: installers/deb, retest-requested
