### ISSUE TITLE
symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy

### ISSUE THREAD

**Issue by zhuker** [shiftkey/desktop#164] opened 2019-07-05 09:09 UTC
## Description

github desktop wont start on ubuntu 18.04

## Version

* GitHub Desktop: 2.1.0-linux1

* Operating system: Ubuntu 18.04

## Steps to Reproduce

1. install github desktop via snap 
`github-desktop          2.1.0-linux1                63    beta      snapcrafters      classic`
2. start `github-desktop`

### Expected Behavior

app launches

### Actual Behavior

`/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy`

**Comment by Jord-JD** [comment] 2019-07-05 09:37
This is a duplicate of #163. The workaround at the moment is to just use a previous version of the snap, or to use the deb package.

**Comment by filippocastelli** [comment] 2019-07-09 09:11
Confirm bug, had to go back to a previous version

**Comment by davidvavra** [comment] 2019-07-16 09:49
How to revert to a previous snap version? I tried:

`$ sudo snap revert github-desktop`

but I get this error:

`error: cannot revert "github-desktop": no revision to revert to`

**Comment by immackay** [comment] 2019-07-17 03:48
If you don't have version 62 cached, you can download it (2.0.4) from the release assets [here](https://github.com/shiftkey/desktop/releases), and install it with

`snap remove github-desktop`
`snap install GitHubDesktop-linux-2.0.4-linux1.snap --classic --dangerous`

**Comment by shiftkey** [comment] 2019-07-21 14:07
Thanks for the report and the workaround! I'm going to roll this into #163 for now as they appear to be the same root cause.

The Snapcraft docker tooling was updated recently and I opened #162 to get it back working, and I'll investigate what's changed later this week now that I'm back from holidays to figure out why it's not working in some distros.

**Closed as completed by shiftkey** 2019-07-21 14:07 UTC
