### ISSUE TITLE
"Sign in using your browser" doesn't work with AppImage

### ISSUE THREAD

**Issue by anowlcalledjosh** [shiftkey/desktop#10] opened 2017-12-14 21:14 UTC
### Description

When prompted to sign in to the app, the "Sign in using your browser" option doesn't work.

### Version

**GitHub Desktop version:** 1.0.11

**OS version:** Ubuntu 16.04.3

### Steps to Reproduce

1. Launch the app for the first time
1. Press buttons until you can choose to sign in in a browser, and do so
1. Go through the OAuth prompts
1. Finish the OAuth prompts, and the redirect to the app doesn't work – you get prompted (by Chrome) to open `xdg-open`, but the webpage doesn't close, and the GitHub app just sits there with the loading spinner until you press Cancel.

**Expected behavior:** Signing in through a browser should work

**Actual behavior:** The redirect back to the app doesn't work

**Reproduces how often:** Presumably always, at least when using the AppImage

### Logs

Can't find these on Linux, will happily provide if someone tells me where they are

**Comment by shiftkey** [comment] 2017-12-14 22:10
This is an old Electron issue https://github.com/electron/electron/issues/6440 and it looks like it will be available in 1.8.2 https://github.com/electron/electron/pull/10670 (we're on `1.7.9`, but `1.8.x` is a major Chromium update for us which we usually do with caution to ensure a smooth transition for users).

**Comment by theel0ja** [comment] 2018-02-27 15:19
Same with .deb version

**Comment by shiftkey** [comment] 2018-02-27 21:00
We're currently testing updating Electron to 1.8.2 in Desktop in [this PR](https://github.com/desktop/desktop/pull/3958), so once that is merged I'll prepare a new build and confirm this is resolved.

**Comment by iAmWillShepherd** [comment] 2018-02-28 17:19
Just tested this in Mint using `bump-electron` and while it will open up my browser (this is an improvement), it won't attempt to start the auth process. If my browser is open, it starts the auth process but never completes.

**Comment by shiftkey** [comment] 2018-02-28 21:46
@iAmWillShepherd to troubleshoot further, do you see [this code](https://github.com/desktop/desktop/blob/60853940d631ae81f2bd383d41e2eea3a6356c62/app/src/main-process/main.ts#L82-L90) being invoked at all when the app is running - probably needs logging as this is in the main process. Maybe a different set of args is being passed to the app and it's not handling them correctly?

**Comment by iAmWillShepherd** [comment] 2018-03-01 16:41
```ts
function handleAppURL(url: string) {
  log.info(`handeledAppUrl::url - ${url}`)
  log.info('Processing protocol url')
  const action = parseAppURL(url)
  onDidLoad(window => {
    // This manual focus call _shouldn't_ be necessary, but is for Chrome on
    // macOS. See https://github.com/desktop/desktop/issues/973.
    window.focus()
    window.sendURLAction(action)
  })
}
```
☝️ never get's called for me. I also pulled in the latest changes from master and tried again. No luck.

**Comment by shiftkey** [comment] 2018-03-27 01:50
We've just released [`1.1.1`](https://github.com/shiftkey/desktop/releases/tag/release-1.1.1) which is based on Electron 1.8.3, so I'd like to figure out what additional work we need to do in the application to support the protocol handler that Electron should be registering correctly on Linux now...

**Comment by ThomasThelen** [comment] 2018-04-14 04:49
This sounds similar to what I just experienced after using the `GitHubDesktop-linux-amd64-1.1.1.deb` installer.

# Summary
When authenticating with oauth & GitHub, Firefox isn't sure what to do with the `x-github-client` protocol. GitHub Desktop seems to wait (the login spinner spins) for a response (which never gets sent out) 

# Steps to Reproduce
1. Launch the app for the first time
2. Press buttons until you can choose to sign in in a browser, and do so
3. Go through the OAuth prompts
4. Confirm password
5. See the following message from firefox with `x-github-client://oauth?code=my_oauth_code` as the url

```
The address wasn’t understood

Firefox doesn’t know how to open this address, because one of the following protocols (x-github-client) isn’t associated with any program or is not allowed in this context.

    You might need to install other software to open this address.
```

     
**Expected  Behavior:** Github Desktop tells me that I've successfully logged in 

**Actual Behavior:** Github Desktop stays in a state with a spinning `Sign In` button.

**Browser:** Firefox 59.0.2 (64-bit)
**OS:** Ubuntu Desktop 17.10

It may be a an issue with the OS/Browser figuring out what to do with `x-github-client` as the protocol.

**Comment by probonopd** [comment] 2018-04-14 08:57
How is Firefox supposed to know what to do with `x-github-client://`? Possibly the launcher script in the AppImage would have to copy a little helper file somewhere to "teach" Firefox what to do with this URL?

**Comment by shiftkey** [comment] 2018-04-14 09:37
Some extra context on this:

Electron is invoking `xdg-settings` to associate the running app with a given protocol. The source for that is [here](https://github.com/electron/electron/blob/f7786a9e4829183cb4eab93fad06a958193f099c/atom/browser/browser_linux.cc#L43-L58).

I'm also pretty sure that Firefox uses XDG to resolve these protocol handlers: https://superuser.com/questions/162092/how-can-i-register-a-custom-protocol-with-xdg

However I can't seem to validate this worked for Desktop `v1.1.1` on my Ubuntu VM - this command doesn't emit any output:

```shellsession
$ xdg-settings get default-url-scheme-handler x-github-client
```

I also get the exact same error from Firefox when trying to complete the auth flow.

**Comment by ascendancyy** [comment] 2018-06-15 02:57
The app protocols need to be added to `script/electron-builder-linux.yml`. In `electron-packager` the protocols are only used for mapping to `CFBundleURLSchemes`. Meanwhile the protocols in the `electron-builder` config are used to add the `MimeType` entry to the app's desktop file.

**Comment by shiftkey** [comment] 2018-06-15 09:20
@ascendancyy got an example of this that I can adapt? The AppImage options listed in [the docs](https://www.electron.build/configuration/linux) don't seem to mention it, and it sounds like an easy change to introduce and validate.

**Comment by ascendancyy** [comment] 2018-06-15 21:32
@shiftkey 

It's a top level [key](https://www.electron.build/configuration/configuration#PlatformSpecificBuildOptions-protocols) - the same values from [here](https://github.com/shiftkey/desktop/blob/linux/script/build.ts#L150-L161).

**Comment by shiftkey** [comment] 2018-08-12 15:25
I've had some time to poke into this, and before I go and try to upstream this or put together a new build could someone sanity check that this change?

```
diff --git a/script/electron-builder-linux.yml b/script/electron-builder-linux.yml
index 604bea24e..a58e8e8f0 100644
--- a/script/electron-builder-linux.yml
+++ b/script/electron-builder-linux.yml
@@ -9,3 +9,7 @@ linux:
     - rpm
     - AppImage
   maintainer: 'GitHub, Inc <opensource+desktop@github.com>'
+deb:
+  mimeTypes:
+    - x-github-client
+    - x-github-desktop-auth
```

Generating this `desktop.desktop` file for the `.deb` file:

```
[Desktop Entry]
Name=GitHubDesktop
Comment=Simple collaboration from your desktop
Exec="/opt/GitHubDesktop/desktop" %U
Terminal=false
Type=Application
Icon=desktop
StartupWMClass=GitHubDesktop
MimeType=x-github-client;x-github-desktop-auth;
Categories=GNOME;GTK;Development;
```

is what we're expecting to address the issue. @ascendancyy does this seem right?

**Comment by ascendancyy** [comment] 2018-08-14 21:05
@shiftkey looks good to me

**Comment by j-f1** [comment] 2018-12-17 15:32
Same issue with the `.deb` installer on Debian on the Chromebook.

**Comment by probonopd** [comment] 2018-12-21 16:33
You will probably need to run the optional [appimaged](https://github.com/AppImage/appimaged) daemon if you want desktop integration, such as associating `MimeType=x-scheme-handler/x-github-client;x-scheme-handler/x-github-desktop-auth;` to your AppImage.

**Comment by shiftkey** [comment] 2018-12-21 16:37
@probonopd today I learned! Thanks for that clue - if it comes up again down the track I'll see about getting some better guidance for it.

**Closed by shiftkey** 2018-12-21 16:37 UTC
Labels: installers/appimage, installers/deb
