### ISSUE TITLE
yum install github-desktop error -  Invalid version flag: or

### ISSUE THREAD

**Issue by IDiston-VA** [shiftkey/desktop#603] opened 2021-09-22 23:35 UTC
## Operating System/Distribution

Which distribution of Linux are you using?
CentOS 7

### Installer

Which version of the app?
 github-desktop.x86_64 0:2.8.0.linux1-1 

Which installer type?
Using the installation instructions from GitHub 

### What happened?

Provide as much detail as possible. Error messages or output are extremely useful.

Having followed the installation instructions, I get the following error when using the 'yum install'

[ian@localhost ~]$ sudo sh -c 'echo -e "[shiftkey]\nname=GitHub Desktop\nbaseurl=https://packagecloud.io/shiftkey/desktop/el/7/\$basearch\nenabled=1\ngpgcheck=0\nrepo_gpgcheck=1\ngpgkey=https://packagecloud.io/shiftkey/desktop/gpgkey" > /etc/yum.repos.d/shiftkey-desktop.repo'

[ian@localhost ~]$ sudo yum install github-desktop
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.fsmg.org.nz
 * extras: mirror.fsmg.org.nz
 * updates: mirror.fsmg.org.nz
shiftkey/x86_64/signature                                |  833 B     00:00     
shiftkey/x86_64/signature                                | 1.0 kB     00:00 !!! 
Resolving Dependencies
--> Running transaction check
---> Package github-desktop.x86_64 0:2.8.0.linux1-1 will be installed
Error: Invalid version flag: or

**Comment by shiftkey** [comment] 2021-09-23 11:13
Duplicate of #320, please follow along with that issue

**Closed as completed by shiftkey** 2021-09-23 11:13 UTC
