### ISSUE TITLE
Cannot connect to https://rpm.packages.shiftkey.dev/

### ISSUE THREAD

**Issue by DAK404** [shiftkey/desktop#1109] opened 2024-08-12 20:37 UTC
### The problem

Got an error when trying to update packages.

The following is the error message:

```
Repository 'GitHub Desktop' is invalid.
[GitHub Desktop|https://rpm.packages.shiftkey.dev/rpm/] Valid metadata not found at specified URL
History:
 - [|] Error trying to read from 'https://rpm.packages.shiftkey.dev/rpm/'
```

Tried to access the URL in a web browser. Got the following error message:

```
Your connection isn't private
Attackers might be trying to steal your information from rpm.packages.shiftkey.dev (for example, passwords, messages, or credit cards).
net::ERR_CERT_COMMON_NAME_INVALID
```

See image below for full details

### Release version

N/A

### Operating system

Linux; OpenSUSE Tumbleweed

### Log files

```
Retrieving repository 'GitHub Desktop' metadata .......................................................................................................................................................................................................................[error]
Repository 'GitHub Desktop' is invalid.
[GitHub Desktop|https://rpm.packages.shiftkey.dev/rpm/] Valid metadata not found at specified URL
History:
 - [|] Error trying to read from 'https://rpm.packages.shiftkey.dev/rpm/'

Please check if the URIs defined for this repository are pointing to a valid repository.
Warning: Skipping repository 'GitHub Desktop' because of the above error.
```

```
rpm.packages.shiftkey.dev uses encryption to protect your information. When Microsoft Edge tried to connect to rpm.packages.shiftkey.dev this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be rpm.packages.shiftkey.dev, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Microsoft Edge stopped the connection before any data was exchanged.

You can't visit rpm.packages.shiftkey.dev right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.
```

### Screenshots

![Screenshot_20240813_020517](https://github.com/user-attachments/assets/e8ac0549-7f1d-4b47-8459-d4f55c358a21)

**Comment by shiftkey** [comment] 2024-08-13 12:46
Closing as duplicate of #1062 

This is working now, but I'll use that issue to do a brain-dump when I have bandwidth.

**Closed as completed by shiftkey** 2024-08-13 12:46 UTC
