### ISSUE TITLE
Can't add certificate of my school

### ISSUE THREAD

**Issue by EldarKurbanov** [shiftkey/desktop#376] opened 2020-11-15 13:36 UTC
### Describe the bug

When I try to log into the GitHub Desktop on my Ubuntu 20.04 at a school that has an internet connection through a proxy server with the appropriate certificate, the program complains that it doesn't trust the api.github.com domain. Although both Firefox and apt-get works well on my system, since I added this certificate to the ca-certificates shared certificate store. When I click the Add Certificate button in GitHub Desktop, the error window disappears. But if I try to log in to my account again, this error appears.

### Version & OS

Version 2.5.7-linux1
OS: Ubuntu 20.04.1 LTS

### Steps to reproduce the behavior

1. Go to 'File'
2. Click on 'Options'
3. Tap to 'Sign in'

### Expected behavior

Sign in...

### Actual behavior

Certificate trust error.

### Screenshots

![Screenshot 2020-11-15 17-34-29](https://user-images.githubusercontent.com/26843500/99186307-d6dfb800-2768-11eb-8c07-3bc4a7460201.png)

### Logs

[2020-11-15.desktop.production.log](https://github.com/shiftkey/desktop/files/5542420/2020-11-15.desktop.production.log)

### Additional context

GitHub Desktop works well in my school on Windows machines...

**Comment by shiftkey** [comment] 2020-12-17 19:15
@EldarKurbanov thanks for the report, and apologies for the delay in replying.

I used to know how this worked but I can't recall what Electron apps are using on Linux for a certificate store (I suspect whatever Chromium is using, which may not be the same as Firefox).

The error you're seeing is what we surface from [this event](https://www.electronjs.org/docs/api/app?q=certificate#event-certificate-error).

I gather in this case that `Add certificate` doesn't work to resolve the issue? I suspect it doesn't work, because I contributed the flow for Windows several years ago but don't recall anyone looking into it for Linux since.

**Comment by EldarKurbanov** [comment] 2020-12-19 07:17
Yes, it is. "Add certificate" button doesn't work.

**Comment by shiftkey** [comment] 2023-07-11 22:11
Closing this out for now as I'm not able to reproduce this myself and adding self-signed certificates at the OS were not supported on Linux at the time from memory. There's also been enough churn in the Electron ecosystem that there's a callback which may allow the app to accept this certificate which I don't think was there at the time.

Please open a fresh issue if you are encountering this with a more recent version of the app, and I can put together a build that we could use to explore this idea further.

**Closed as not planned by shiftkey** 2023-07-11 22:11 UTC
Labels: unclear, bug, needs-investigation
