### ISSUE TITLE
Crash with white screen after 3.3.5-linux1 update

### ISSUE THREAD

**Issue by calvinbull** [shiftkey/desktop#965] opened 2023-11-28 21:34 UTC
### The problem

After the 3.3.5-linux1 update on 27 Nov 2023, the GH desktop application becomes unresponsive after 1-2 seconds of use. The application window becomes white and unusable. No error message appears. 

Some menu options are still visible. The 'report issue' menu option still functions, but 'About GitHub Desktop' is greyed out.

### Release version

3.3.5-linux1

### Operating system

Pop!_OS 22.04

### Steps to reproduce the behavior

1. Open GH desktop.
2. Wait 1-2 seconds.
3. App freezes, entire window turns white.

### Log files

[2023-11-28.desktop.production.log](https://github.com/shiftkey/desktop/files/13493334/2023-11-28.desktop.production.log)

### Screenshots

![Screenshot from 2023-11-28 16-29-12](https://github.com/shiftkey/desktop/assets/97459530/8817b9c3-5423-4819-9ecd-334855dfd060)

**Comment by shiftkey** [comment] 2023-11-28 22:26
Duplicate of #958, please re-test with the latest release https://github.com/shiftkey/desktop/releases/tag/release-3.3.5-linux2 (has to be installed manually for now) and see if it resolves for your setup.

**Closed as not planned by shiftkey** 2023-11-28 22:26 UTC
