### ISSUE TITLE
A Bug in Ubuntu18.04

### ISSUE THREAD

**Issue by bear-good** [shiftkey/desktop#175] opened 2019-08-27 03:27 UTC
## Description
An error occurred in Ubuntu 18.04, causing the program to fail to run.

## Version

snap install github-desktop --beta --classic

* GitHub Desktop:
* Operating system:
Ubuntu18.04

## Steps to Reproduce
1. Punch terminal (zsh)
1. Enter github-desktop

### Expected Behavior
Github-desktop is running normally

### Actual Behavior
Github-desktop is not working properly and prompts: /snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol : g_date_copy

## Additional Information
None

### Logs
I don't have any logs

**Comment by immackay** [comment] 2019-08-27 04:36
This is an issue with the 2.1.0 snap package, see #163 

There are instructions regarding downgrading to 2.0.4 there.

**Comment by bear-good** [comment] 2019-08-27 04:43
@immackay 
```sh
snap install path/to/GitHubDesktop-linux-2.0.4-linux1.snap --classic

error: cannot open: "path/to/GitHubDesktop-linux-2.0.4-linux1.snap"
```

**Comment by pw24** [comment] 2019-11-18 15:03
same issue found on my machine... running from a Ubuntu VM (for testing purposes), Ubuntu 18.06 LTS.

Installed version 2.1.0
![image](https://user-images.githubusercontent.com/7777405/69066876-d2d06b80-0a2a-11ea-9889-a164cbfb51b8.png)

**Comment by ghost** [comment] 2019-11-24 19:28
@bear-good Did you use the real path or really `path/to/GitHubDesktop-linux-2.0.4-linux1.snap --classic`

**Comment by esosam** [comment] 2019-12-04 22:24
I unistalled the version and when directly to here https://github.com/shiftkey/desktop/releases/tag/release-2.1.0-linux1 and downloaded the deb version for ubuntu, and when ready double click the file and installed on the Ubuntu software app and worked, I follow this link https://www.youtube.com/watch?v=tg3CWTefjCc

**Comment by shiftkey** [comment] 2020-02-07 19:09
Closing this out as a duplicate of #163.

The `deb` installer is recommended until we can get to the bottom of that issue.

**Closed as completed by shiftkey** 2020-02-07 19:09 UTC
Labels: installers/snap
