### ISSUE TITLE
Releases 2.5.5 and 2.5.6 out for Windows and Mac

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#351] opened 2020-10-02 13:27 UTC
### Describe the feature or problem you’d like to solve

Releases 2.5.5 and 2.5.6 out for Windows and Mac

### Proposed solution

Can you please upgrade ?

### Additional context

Thanks a lot

**Comment by shiftkey** [comment] 2020-10-02 13:51
I can't give you an estimate of when I'll get to this because I've been swamped with other work and personal things, and I don't feel like pushing ahead with further updates while #329 and #332 are unresolved from 2.5.4.

I've documented the process I use for testing these updates https://github.com/shiftkey/desktop/blob/linux/docs/process/publishing-linux-releases.md - maybe someone wants to have a go and see if they can test things locally in the meantime?

**Comment by ghost** [comment] 2020-10-02 13:59
For sure i will try next week, i will works night and day for 5 days.

 
 

Envoyé: vendredi 2 octobre 2020 à 15:51
De: "Brendan Forster" <notifications@github.com>
À: "shiftkey/desktop" <desktop@noreply.github.com>
Cc: "hunabku" <hunabku@gmx.com>, "Author" <author@noreply.github.com>
Objet: Re: [shiftkey/desktop] Releases 2.5.5 and 2.5.6 out for Windows and Mac (#351)


 

I can't give you an estimate of when I'll get to this because I've been swamped with other work and personal things, and I don't feel like pushing ahead with further updates while #329 and #332 are unresolved from 2.5.4.

I've documented the process I use for testing these updates https://github.com/shiftkey/desktop/blob/linux/docs/process/publishing-linux-releases.md - maybe someone wants to have a go and see if they can test things locally in the meantime?

**Comment by shiftkey** [comment] 2020-10-24 21:07
Just bumping this thread to let you know that I'm still blocked on resolving #329 and #332, and it feels inappropriate to publish new releases while this issue is impacting users (including myself). I wanted to see if upgrading Electron would fix the issue, but it doesn't seem to change the behaviour.

**Comment by serkonda7** [comment] 2020-10-29 16:53
@shiftkey I would prefer if you could publish a new release even with the two mentioned issues.
Now we have a slightly disturbed workflow AND lack new features from upstream. Publishing a new version would at least solve the second point and give no further drawbacks.

**Comment by shiftkey** [comment] 2020-11-08 17:53
2.5.5, 2.5.6 and 2.5.7 are now listed on the [Releases](https://github.com/shiftkey/desktop/releases) section.

I'll organize getting packagecloud up to date once I've confirmed the builds are stable.

**Closed as completed by shiftkey** 2020-11-08 17:53 UTC
Labels: help wanted, infrastructure
