### ISSUE TITLE
gpg: no valid OpenPGP data found

### ISSUE THREAD

**Issue by timhsanchez1** [shiftkey/desktop#298] opened 2020-06-21 18:29 UTC
### Operating System/Distribution

Ubuntu 20.04 LTS

### Installer

Debian: wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -

### What happened?

I ran the first command listed in the install instructions for Debian/Ubuntu: wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -

This produced the following error: 
gpg: no valid OpenPGP data found

I also went to https://packagecloud.io/shiftkey/desktop/ to see if I could download the .deb file direction. When I click on the download link for github-desktop_2.5.2 (this link: https://packagecloud.io/shiftkey/desktop/packages/any/any/github-desktop_2.5.2-linux1_amd64.deb/download.deb), I get the following message: Bandwidth or Storage Limit Exceeded

Thank you for creating this, I hope I can get it to work.

**Comment by shiftkey** [comment] 2020-06-21 20:40
@timhsanchez1 I'm not familiar with the first issue, but the second one I do know:

>  I get the following message: Bandwidth or Storage Limit Exceeded

This is mentioned in https://github.com/shiftkey/desktop/issues/278#issuecomment-646991072 after my bandwidth being consumed despite bumping the subscription a couple of weeks ago. It should start working again tomorrow when the bandwidth limit resets.

**Comment by shiftkey** [comment] 2020-06-21 20:42
> I also went to https://packagecloud.io/shiftkey/desktop/ to see if I could download the .deb file direction

Each release is listed here on GitHub. Here's the latest release if you still want to install the deb directly: https://github.com/shiftkey/desktop/releases/tag/release-2.5.2-linux1

**Comment by shiftkey** [comment] 2020-06-21 20:45
The first part of the issue is the same underlying problem as the second. If you check that URL in a browser:

<img width="441" src="https://user-images.githubusercontent.com/359239/85234851-dbd15300-b3e6-11ea-9926-dc9929841c74.png">

Will close this out tomorrow when I've confirmed it's working as expected

**Comment by timhsanchez1** [comment] 2020-06-22 01:02
Thank you!

**Comment by shiftkey** [comment] 2020-06-22 16:16
@timhsanchez1 this should be working again :tada:

**Closed as completed by shiftkey** 2020-06-22 16:16 UTC

**Comment by timhsanchez1** [comment] 2020-06-22 16:44
Thanks a lot, it's working! Can I donate $10 to you? I can just Google Pay
you if you have a gmail.

**Comment by shiftkey** [comment] 2020-06-22 17:36
> Can I donate $10 to you? I can just Google Pay you if you have a gmail.

I'm afraid I don't. I'd prefer to use GitHub Sponsors for this if possible.
