### ISSUE TITLE
The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

### ISSUE THREAD

**Issue by kazunetakeda25** [shiftkey/desktop#945] opened 2023-10-16 01:13 UTC
### The problem

After sign in , I can't pull or fetch from private repository

![image](https://github.com/shiftkey/desktop/assets/58710601/727b023d-b70a-4182-87eb-9eb3062387cc)

### Release version

Version 3.3.1-linux1 (x64)

### Operating system

Ubuntu 22.04

### Steps to reproduce the behavior

1. File => Options => Sign Out
2. File => Options => Sign In and Continue From Browser
3. Git Fetch
4. Error: The repository does not seem to exist anymore. You may not have access, or it may have been deleted or renamed.

### Log files

[2023-10-16.desktop..log](https://github.com/shiftkey/desktop/files/12911173/2023-10-16.desktop.log)

**Comment by andygeorge** [comment] 2023-10-16 20:25
Possible duplicate of https://github.com/shiftkey/desktop/issues/942

**Comment by shiftkey** [comment] 2023-10-24 23:16
From the logs:

```
2023-10-16T01:11:29.811Z - info: [ui] [fetchPushControl] unable to check if branch is potentially pushable
Error: Although you appear to have the correct authorization credentials, the `amberfi-xyz` organization has enabled OAuth App access restrictions, meaning that data access to third-parties is limited. For more information on these restrictions, including how to enable this app, visit https://docs.github.com/articles/restricting-access-to-your-organization-s-data/
```

**Comment by shiftkey** [comment] 2023-10-24 23:30
This is related to organization settings and OAuth App access restrictions, and not something that I can fix easily.

**Closed by shiftkey** 2023-10-24 23:30 UTC
