### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by pervoj** [shiftkey/desktop#405] opened 2021-01-03 13:23 UTC
### Describe the bug

When I want to login to GitHub, application opens Firefox and Firefox writes (in Czech):
![obrazek](https://user-images.githubusercontent.com/71781857/103479465-12444d80-4dce-11eb-97e7-d2070bbbdd2d.png)
English translation: _Address not recognized: An error occurred while connecting to github.com. You may need to install additional software to open this address._

### Version & OS

Open 'About GitHub Desktop' menu to see the Desktop version. Also include what operating system you are using.

Version: 2.5.4-linux1
OS: Linux Mint 20 - Cinnamon

### Steps to reproduce the behavior

1. Go to `File` -> `Options...` -> `Accounts` -> `GitHub.com` -> `Sign in`
2. Now it opens Firefox and you see the error

### Expected behavior

It shows login form to GitHub

### Actual behavior

Application opened Firefox with error.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

> 2021-01-03T13:21:37.346Z - info: [ui] [SignInStore] initializing OAuth flow
> 2021-01-03T13:21:37.363Z - info: [main] opening in browser: https://github.com/login/oauth/authorize?client_id=3a723b10ac5575cc5bb9&scope=repo%20user%20workflow&state=e53dcfa5-821e-427c-b6ad-55d138f5efac

**Comment by fubuki4649** [comment] 2021-01-03 18:56
Same issue on Debian 10.7

**Comment by JanzenJohn** [comment] 2021-01-04 10:39
Same issue on Manjaro kernel 5.9.16-1-MANJARO

Latest release GitHub desktop
Downloaded as an AppImage

**Comment by DeflatedPickle** [comment] 2021-01-04 13:44
I'm getting the same issue on PopOS so I think this issue is specific to this project rather than a distribution-based problem. I was able to login with GitKracken, so it might be that if the logging in needs some authentication key, that it was revoked?

**Comment by shiftkey** [comment] 2021-01-04 14:13
> Address not recognized: An error occurred while connecting to github.com. You may need to install additional software to open this address.

This error is very vague, but maybe it's related to the protocol handlers that Desktop needs to launch after the OAuth flow has completed? I'm not sure what else to check at the moment.

> Version: 2.5.4-linux1

This version is from August, and the latest version is [`2.6.1-linux2`](https://github.com/shiftkey/desktop/releases/tag/release-2.6.1-linux2). Please confirm this is happening with the latest version.

> Latest release GitHub desktop
> Downloaded as an AppImage

I don't think AppImage will install any protocol handlers to re-launch the app, which could be part of the issue here - it's not clear to me which installation source was used for the others.

> I'm getting the same issue on PopOS so I think this issue is specific to this project rather than a distribution-based problem. I was able to login with GitKracken, so it might be that if the logging in needs some authentication key, that it was revoked?

This depends on the type of package installed, but I'm not aware of any changes in that area.

**Comment by pervoj** [comment] 2021-01-04 14:17
The same error occurs in version 2.6.1.

**Comment by DeflatedPickle** [comment] 2021-01-04 14:48
I didn't think to check my version - I installed it through the PopOS store, but it doesn't seem to have been updated in a bit as it's `2.4.1-linux1`

Edit: I installed the latest release from GitHub and I was able to log in through the browser, after a popup to launch the link with Desktop and a popup to log in to Linux. I'm just an idiot

**Comment by pervoj** [comment] 2021-01-15 15:19
I tried to do login process with Opera Browser, but same problem.

**Comment by shiftkey** [comment] 2021-01-24 15:12
I can spot some known issues in here which are covered elsewhere:

 - #414 is the Pop_OS and PopStore version being out of date, which I'm not involve with maintaining
 - #416 is tracking the AppImage and the browser callback not working as expected (needs investigation to understand the resolution) 

I've collapsed those comments for now. That leaves @pervoj @kugelblitz2 - it's not clear to me whether you're using the AppImage as well. Can you confirm which installer you're using to confirm this is our known issue or some other setup?

**Comment by pervoj** [comment] 2021-01-27 10:08
I installed app as DEB package.

**Comment by yonderbread** [comment] 2021-01-27 21:35
I'm unable to login to my Github account at all. Any fix for this?

**Comment by shiftkey** [comment] 2021-01-31 17:16
> I installed app as DEB package.

@pervoj we rely on `MimeType` configuration value in the `.desktop` file to signal to the browser to launch our app:

https://github.com/shiftkey/desktop/blob/a63a8655b42165230dac3b01ca5ea5eceb7f8e38/script/package-debian.ts#L67-L75

And that should be present after installation:

```
$ ls /usr/share/applications/github-desktop.desktop | grep MimeType
MimeType=x-scheme-handler/x-github-client;x-scheme-handler/x-github-desktop-auth;x-scheme-handler/x-github-desktop-dev-auth;
```

I've assumed this works fine (I'm on Firefox on Ubuntu) and it hasn't changed in several releases ([`2.4.1-linux2`](https://github.com/shiftkey/desktop/releases/tag/release-2.4.1-linux2) was when I last changed this packaging, but we were using the same approach as before). So I'm kinda stumped on what else to try with your setup to understand the root cause.

> I'm unable to login to my Github account at all. Any fix for this?

@yonderbread please open a [new bug report](https://github.com/shiftkey/desktop/issues/new?assignees=&labels=&template=bug_report.md&title=) and fill out the template so we can handle that separate to this discussion.

**Comment by pervoj** [comment] 2021-02-08 14:26
I solved it. I reinstalled Linux Mint yesterday and the login already works on a fresh installation. I do not get it.

**Comment by shiftkey** [comment] 2021-02-11 16:54
Closing this out as I don't think there's anything left to investigate around this 🤷🏻

**Closed as completed by shiftkey** 2021-02-11 16:54 UTC
Labels: unclear
