### ISSUE TITLE
cannot change token to authenticate to custom Git server

### ISSUE THREAD

**Issue by TrevCan** [shiftkey/desktop#688] opened 2022-04-03 18:00 UTC
### Search existing issues

- [X] I have searched the issue tracker and confirmed that I was unable to find existing issues for the problem I am experiencing.

### The problem

When setting up github desktop for the first time, I tried to clone an https repository that I self-host. Github desktop asked for the password, but I entered it incorrectly. When trying to clone it, even to another folder, it endlessly keeps hanging forever. **I do not see anywhere an option to change the https access credentials.** 

Plus, the github desktop client itself just keeps 'loading' endlessly and does not provide feedback on why it is failing (e.g. in this case it would be https authentication)

I can confirm I can clone the repository from the normal git client thru https, with http authentication.

### Release version

Version 2.9.6-linux1 (x64)

### Operating system

Arch Linux 5.17.1-zen1-1-zen DWM

### Steps to reproduce the behavior

1. Get a git remote url repo with an https link.
2. purposefully enter the 'wrong' credentials into the authentication prompt.
3. try cloning again, does it work ?
4. try changing the auth user/password.

### Log files

**edit: log files are indeed created, just not show in my file manager. the log file is in another comment**

No log files are created by Github Desktop, even when clicking on `Help -> Show logs`

### Additional context

I understand that github implements the http transport without authentication when cloning repositories, making it unnecessary to provide access credentials. But it seems a little redundant to not provide these if I were to have an https server that **does require** them.

**Comment by shiftkey** [comment] 2022-04-03 18:12
>  When trying to clone it, even to another folder, it endlessly keeps hanging forever. I do not see anywhere an option to change the https access credentials.

The OAuth token is stored in your keychain, so you can delete or override it there from your OS settings if so desired.

> Plus, the github desktop client itself just keeps 'loading' endlessly and does not provide feedback on why it is failing (e.g. in this case it would be https authentication)

I'm curious what the log files located at **Help** | **Show logs in your File Manager..** show here - we're shelling out to `git` to do the clone and I wonder what output or exit codes it's receiving from the remote.

**Comment by thyeun** [comment] 2022-04-03 18:49
@TrevCan Github Desktop always will create a log file, Best way to get it is, you go to your `~/.config/GitHub Desktop/logs/` and look for the file latest date&time, than open it with any text editor, with that, you will possible to show/paste the log file here.

**Comment by fanninpm** [comment] 2022-04-03 18:54
> Version 2.9.6-linux1 (x64)

Have you tried it on any later version?

**Comment by TrevCan** [comment] 2022-04-03 22:20
Hello, thanks for the replies. 

It literally just stays there hanging:

![image](https://user-images.githubusercontent.com/44383325/161451119-ac98d5d0-f452-42ce-b881-be08bce42e0c.png)

@thyeun apparently there were indeed logs, but for some reason my file manager isn't showing them. But doing an `ls` of the directory does indeed show a log of today.

**Comment by TrevCan** [comment] 2022-04-03 22:22
Log:
<details>
  <summary>log: 2022-04-03.desktop.production.log </summary>
<code><pre>
2022-04-03T16:37:43.128Z - info: [ui] [AppStore] loading 0 repositories from store
2022-04-03T16:37:43.386Z - info: [ui] launching: 2.9.6-linux1 (Linux 5.17.1-zen1-1-zen)
2022-04-03T16:37:43.388Z - info: [ui] execPath: '/opt/github-desktop/github-desktop'
2022-04-03T16:37:44.603Z - info: [ui] Stats reported.
2022-04-03T16:38:08.424Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'https://git-push.thetrevor.tech/space-girls.git'
2022-04-03T16:38:09.008Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=master clone --recursive --progress -- https://git-push.thetrevor.tech/space-girls.git /home/trevorlarbs/Documents/GitHub` exited with an unexpected code: 128.
stderr:
Cloning into '/home/trevorlarbs/Documents/GitHub'...
fatal: Authentication failed for 'https://git-push.thetrevor.tech/space-girls.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:

- You are not logged in to your account: see File > Options.
- You may need to log out and log back in to refresh your token.
- You do not have permission to access this repository.
- The repository is archived on GitHub. Check the repository settings to confirm you are still permitted to push commits.
- If you use SSH authentication, check that your key is added to the ssh-agent and associated with your account.
- If you use SSH authentication, ensure the host key verification passes for your repository hosting service.
- If you used username / password authentication, you might need to use a Personal Access Token instead of your account password. Check the documentation of your repository hosting service.)
2022-04-03T16:38:16.322Z - info: [ui] storing generic credentials for 'git-push.thetrevor.tech' and 'aa'
2022-04-03T16:38:16.364Z - error: [ui] Error saving generic git credentials: aa@git-push.thetrevor.tech
Error: The name org.freedesktop.secrets was not provided by any .service files
2022-04-03T16:38:16.365Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'git-push.thetrevor.tech' and 'aa'
2022-04-03T16:38:49.383Z - info: [ui] [AppStore] loading 0 repositories from store
2022-04-03T16:38:49.610Z - info: [ui] launching: 2.9.6-linux1 (Linux 5.17.1-zen1-1-zen)
2022-04-03T16:38:49.611Z - info: [ui] execPath: '/opt/github-desktop/github-desktop'
2022-04-03T16:40:10.669Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'git-push.thetrevor.tech' and 'aa'
2022-04-03T16:42:00.311Z - info: [ui] [AppStore] loading 0 repositories from store
2022-04-03T16:42:00.547Z - info: [ui] launching: 2.9.6-linux1 (Linux 5.17.1-zen1-1-zen)
2022-04-03T16:42:00.549Z - info: [ui] execPath: '/opt/github-desktop/github-desktop'
2022-04-03T16:42:27.057Z - info: [ui] Opt out reported.
2022-04-03T16:42:41.786Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'git-push.thetrevor.tech' and 'aa'
2022-04-03T17:41:45.836Z - info: [ui] [AppStore] loading 0 repositories from store
2022-04-03T17:41:45.979Z - info: [ui] launching: 2.9.6-linux1 (Linux 5.17.1-zen1-1-zen)
2022-04-03T17:41:45.980Z - info: [ui] execPath: '/opt/github-desktop/github-desktop'
2022-04-03T17:42:16.099Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'git-push.thetrevor.tech' and 'aa'
2022-04-03T17:51:12.052Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'https://git-trevcan.duckdns.org/space-girls.git/'
2022-04-03T17:51:13.835Z - info: [ui] Executing clone: git -c credential.helper= -c init.defaultBranch=master clone --recursive --progress -- https://git-trevcan.duckdns.org/space-girls.git/ /home/trevorlarbs/GitHub/ssss (took 1.666s)
2022-04-03T17:51:13.852Z - info: [ui] [AppStore] adding repository at /home/trevorlarbs/GitHub/ssss to store
2022-04-03T22:15:11.156Z - info: [ui] [AppStore] loading 1 repositories from store
2022-04-03T22:15:12.485Z - info: [ui] launching: 2.9.6-linux1 (Linux 5.17.1-zen1-1-zen)
2022-04-03T22:15:12.486Z - info: [ui] execPath: '/opt/github-desktop/github-desktop'
2022-04-03T22:15:54.511Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'git-push.thetrevor.tech' and 'aa'

</pre></code>
</details>

**Comment by TrevCan** [comment] 2022-04-03 22:32
> > Version 2.9.6-linux1 (x64)
> 
> Have you tried it on any later version?

no, it seems like the `makepkg` command in the aur is not allowing me to install it unless I have `gnome-keyring` installed. Problem is, the `gnome-keyring` package has given me lots of trouble and it conflicts with some software I run.

**edit: ** I've just tried it on `2.9.12-3` (the latest version on the AUR) and it still does not work, it keeps hanging! Even with all the dependencies ( including `gnome-keyring` installed ).

**Comment by thyeun** [comment] 2022-04-04 01:30
@TrevCan Since you are using SSH as your credentials, you have to re-do your credentials at github for your `space-girls.git`, and follow the instruction for setting up your pc SSH too. Once it matching, i think your issue will be gone.

And for your Github Desktop, before you launching your login, setting on your `Git`, `Name` and `Email` should matching to your github account also.

**Comment by TrevCan** [comment] 2022-04-04 01:39
@thyeun I am not using ssh, I am using the [smart git http](https://git-scm.com/book/en/v2/Git-on-the-Server-Smart-HTTP) protocol.

**Comment by thyeun** [comment] 2022-04-04 01:53
@TrevCan Can you go to your `github setting` and look for `SSH and PGP keys`, do you enable anything at there?

**Comment by shiftkey** [comment] 2022-04-04 13:46
@TrevCan thanks for the log file. That helps me to explain a bit more about what I believe is happening.

When doing Git operations involving a remote, the app will work through a few steps:

 - check for any credentials it stored previously,
 - if none found, try and clone without providing credentials (e.g. public repository)
 - if that fails, prompt the user and try again

```
2022-04-03T16:38:08.424Z - info: [ui] [AppStore.getAccountForRemoteURL] no generic credentials found for 'https://git-push.thetrevor.tech/space-girls.git'
2022-04-03T16:38:09.008Z - error: [ui] `git -c credential.helper= -c init.defaultBranch=master clone --recursive --progress -- https://git-push.thetrevor.tech/space-girls.git /home/trevorlarbs/Documents/GitHub` exited with an unexpected code: 128.
stderr:
Cloning into '/home/trevorlarbs/Documents/GitHub'...
fatal: Authentication failed for 'https://git-push.thetrevor.tech/space-girls.git/'

(The error was parsed as 3: Authentication failed. Some common reasons include:
// snip
2022-04-03T16:38:16.322Z - info: [ui] storing generic credentials for 'git-push.thetrevor.tech' and 'aa'
2022-04-03T16:38:16.364Z - error: [ui] Error saving generic git credentials: [aa@git-push.thetrevor.tech](mailto:aa@git-push.thetrevor.tech)
Error: The name org.freedesktop.secrets was not provided by any .service files
2022-04-03T16:38:16.365Z - info: [ui] [AppStore.getAccountForRemoteURL] found generic credentials for 'git-push.thetrevor.tech' and 'aa'
```

What's weird here is that it both seems to succeed and fail to store the credentials you provided. I'm sceptical that it's actually working given you mention it seems to hang. The "saving generic git credentials" step followed by this message suggests it _started to save_ but didn't complete, which is my working theory given you also mention problems with `gnome-keyring`:

```
Error: The name org.freedesktop.secrets was not provided by any .service files
```

The app isn't actually tied to `gnome-keyring`, this was just the one that I know supports `libsecret` and is mainstream. KWallet talked about support years ago but it never eventuated, and I've not kept up with the alternatives. The app interact with the credential store on the local machine using `libsecret`, so any backend that knows how to respond should work. If you're bold enough to hack on the `PKGBUILD` for this and have a different store that you prefer it may work fine - e.g. [this comment](https://aur.archlinux.org/packages/github-desktop-bin#comment-853517) mentions [`keepassxc`](https://archlinux.org/packages/community/x86_64/keepassxc/).

The app doesn't manage credentials directly, and using an operating system-backed mechanism here is the same as what we do for Windows and macOS, so it'd be great to figure out how to get a backing store for credentials working with your setup.

**Comment by fanninpm** [comment] 2022-04-05 00:24
> KWallet talked about support years ago but it never eventuated

[There has been progress, but it has been slow.](https://invent.kde.org/frameworks/kwallet/-/merge_requests/11)

**Comment by shiftkey** [comment] 2022-06-25 18:15
Closing this out as I don't think I have anything else to add about the credential store issue that's the root cause here.

**Closed as not planned by shiftkey** 2022-06-25 18:15 UTC
Labels: dbus
