### ISSUE TITLE
Problems with packagecloud

### ISSUE THREAD

**Issue by nayvcake** [shiftkey/desktop#335] opened 2020-09-04 15:16 UTC
### Operating System/Distribution
Which distribution of Linux are you using?
Linux Mint
### Installer

Which version of the app?
Which installer type?

### What happened?
I'm having problems downloading the keys from packagecloud and unfortunately I'm getting this error "Bandwidth or Storage Limit Exceeded" when I download this key I also get this error "gpg: no valid OpenPGP data found."
![error](https://user-images.githubusercontent.com/43297329/92255166-4b17f880-eea8-11ea-8407-343f9220c219.png)

Command that was used that gave this problem:
`wget -qO - https://packagecloud.io/shiftkey/desktop/gpgkey | sudo apt-key add -`

**Comment by jhunterkohler** [comment] 2020-09-04 23:06
I can second this issue. 

### Terminal Response
`gpg: no valid OpenPGP data found.`

### Operating System
Ubuntu 20.04.1 LTS

**Comment by KevinOlivieri** [comment] 2020-09-05 15:25
I have the same issue with Linux GT2000 5.7.0-kali3-amd64 #1 SMP Debian 5.7.17-1kali1 (2020-08-26) x86_64 GNU/Linux
"Bandwidth or Storage Limit Exceeded" 
Err:3 https://packagecloud.io/shiftkey/desktop/any any InRelease
  429  Too Many Requests [IP: xx.xx.xx.xx 443]
Reading package lists... Done
W: Failed to fetch https://packagecloud.io/shiftkey/desktop/any/dists/any/InRelease  429  Too Many Requests [IP: xx.xx.xx.xx 443]

**Comment by nayvcake** [comment] 2020-09-05 15:41
For someone who is having trouble downloading this package I recommend you download it through the **[releases](https://github.com/shiftkey/desktop/releases)**

Releases: https://github.com/shiftkey/desktop/releases

**Comment by sgornick** [comment] 2020-09-07 05:06
This is a duplicate of #310

**Comment by shiftkey** [comment] 2020-09-07 21:21
As I said in #310:

> Yep, I've had another month where the bandwidth limit on Packagecloud (165GB) is reached early, so the account gets suspended.
> 
> It's costing me USD $150 per month to cover and I've asked for [support with covering these costs from the community](https://github.com/sponsors/shiftkey) so until that's covered I'm not keen to extend myself further.

The billing cycle resets around the 22nd of the month, so I'd recommend the manual install in the meantime. But if you are able to help with sponsorship costs (currently only 20% is covered by the community), it'd be neat to take this up to the next subscription level so it's available to more users, which is $300 per month.

**Closed as completed by shiftkey** 2020-09-07 21:21 UTC
