### ISSUE TITLE
Couldn't parse author identity

### ISSUE THREAD

**Issue by ghost** [shiftkey/desktop#373] opened 2020-11-11 23:17 UTC
Steps to reproduce:

Try with this repo:
https://android.googlesource.com/platform/bootable/recovery/+/refs/heads/master

The error:
Couldn't parse author identity for '25a5e744'

**Comment by ghost** [comment] 2020-11-11 23:19
GitHub Desktop 2.5.7 on Ubuntu 20.04.1 LTS

**Comment by shiftkey** [comment] 2020-12-17 19:03
@test-acc-vaccym apologies for the delay on this. This error occurs when we're not able to understand the commit details emitted by Git:

https://github.com/shiftkey/desktop/blob/4d211486ea7d99b160dcc1802796ebef8f5515a0/app/src/lib/git/log.ts#L135-L139

I wasn't able to reproduce this on `2.5.7-linux1` myself but it looks like this is the related commit from the log:

https://android.googlesource.com/platform/bootable/recovery/+/25a5e7441981efd5a2d174a060d5d5fa031e1ffe

I tried to checkout this commit directly and see the error myself but it works fine:

![](https://user-images.githubusercontent.com/359239/102531537-d47ac180-4078-11eb-8a35-9a9ed386c752.png)

Any extra details about reproducing this would be greatly appreciated, if you are still encountering it. Otherwise I'm going to close this out next week.

**Comment by ghost** [comment] 2020-12-24 16:05
@shiftkey I can confirm that checking directly works. The steps I did which reproduces the error:

1. repo init -u https://android.googlesource.com/platform/manifest -b android-11.0.0_r18
2. repo sync -j48
3. GitHub Desktop -> Add local repo -> bootable/recovery
 
I'm not sure if that is possible for you to verify since this will at first download AOSP source code which is around 100gb. There are more repos within AOSP that would trigger this error.

**Closed as completed** 2021-08-13 19:17 UTC
Labels: unclear
