### ISSUE TITLE
cannot sign in

### ISSUE THREAD

**Issue by boobiesboob** [shiftkey/desktop#682] opened 2022-03-25 14:16 UTC
### Describe the bug
Write a clear and concise description of what the bug is.

cannot sign in on fedora. connecting status the whole time

### Version & OS

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Expected behavior

Write a clear and concise description of what you expected to happen.

### Actual behavior

Write a clear and concise description of what actually happened.

### Screenshots

Add screenshots to help explain your problem, if applicable.

### Logs

Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

**Comment by K0-RR** [comment] 2022-03-25 22:57
Please... PLEASE look at the current issues before opening your own. It takes 5 seconds.
Duplicate of https://github.com/shiftkey/desktop/issues/681 https://github.com/shiftkey/desktop/issues/680 https://github.com/shiftkey/desktop/issues/677 https://github.com/shiftkey/desktop/issues/676 https://github.com/shiftkey/desktop/issues/674 https://github.com/shiftkey/desktop/issues/673 https://github.com/shiftkey/desktop/issues/672 https://github.com/shiftkey/desktop/issues/670 https://github.com/shiftkey/desktop/issues/669 https://github.com/shiftkey/desktop/issues/668 https://github.com/shiftkey/desktop/issues/666. There is a walkaround in the original issue.

**Comment by shiftkey** [comment] 2022-04-03 16:01
> cannot sign in on fedora. connecting status the whole time

Closing this out as incomplete - I don't know enough about what versions of things you have installed, or any log files or error messages to investigate further...

**Closed as completed by shiftkey** 2022-04-03 16:01 UTC
