### ISSUE TITLE
Github Desktop not authorizing in

### ISSUE THREAD

**Issue by Sodiograaz** [shiftkey/desktop#668] opened 2022-02-27 23:58 UTC
### Version & OS

OS Arch linux x86_64
Kernel (idk if it's useful to this bug): 5.15.7-arch1-1 

Open the 'About GitHub Desktop' menu to see the GitHub Desktop version. Also include what operating system you are using.

### Steps to reproduce the behavior

1. Open Github Desktop (Actually i have tried all the version for Arch Linux which are AUR and AppImage)
2. Click on Sign in
3. Authorize the app
4. See error which is: 
   `URL Action: unknown - payload: {"name":"unknown","url":"--enable-crashpad"}`

### Expected behavior
The Actual Sign in

### Actual behavior

Complete loop for Sign in button

### Screenshots

![image](https://user-images.githubusercontent.com/59530630/155905474-76b10475-92be-4b6a-887b-066312730b6a.png)

### Logs

[2022-02-27.desktop.production.log](https://github.com/shiftkey/desktop/files/8149659/2022-02-27.desktop.production.log)

**Comment by jnv** [comment] 2022-02-28 10:04
Duplicate of #666

**Closed as completed** 2022-03-04 08:40 UTC
