### ISSUE TITLE
Authentication Failed - Github Desktop Ubuntu

### ISSUE THREAD

**Issue by vin-fandemand** [shiftkey/desktop#305] opened 2020-06-29 16:42 UTC
### Describe the feature or problem you’d like to solve

Trying to clone a private repo from my organization. On entering the user name and password,  I get a pop up saying "Authentication failed We were unable to authenticate with github.com. Please enter your username and password to try again."

### Additional context

I am using the Ubuntu distribution. I am able to clone my own repos and public repos from my org.  

![image](https://user-images.githubusercontent.com/64597233/85928286-ea51bb80-b879-11ea-9d79-003fc38e0672.png)

**Comment by vin-fandemand** [comment] 2020-06-29 16:51
I am guessing this is same as #281

From all the similar issues raised, I guess you understand how important it is for the dev community.

**Comment by shiftkey** [comment] 2020-06-29 17:31
> From all the similar issues raised, I guess you understand how important it is for the dev community.

I'm deferring to the GitHub Desktop team about this support and have outlined the other options available, none of which really address the core of the problem: https://github.com/shiftkey/desktop/issues/72#issuecomment-606599547

**Comment by shiftkey** [comment] 2020-06-29 17:32
Closing this out as #72 is the root cause of the issue

**Closed as completed by shiftkey** 2020-06-29 17:32 UTC
