### ISSUE TITLE
Log-in doesn't work

### ISSUE THREAD

**Issue by Micharoll** [shiftkey/desktop#681] opened 2022-03-24 12:04 UTC
### Operating System/Distribution

elementary os latest version(6.1)

### Installer

2.9.9 linux RC 2
dpkg .deb file in terminal

### What happened?

I can't log-in because browser's link doesn't work.

![Screenshot from 2022-03-24 11-58-43](https://user-images.githubusercontent.com/85116587/159912081-c9e028c5-5cee-4499-9088-872134ddd580.png)

**Comment by K0-RR** [comment] 2022-03-24 12:29
What is wrong with these people... PLEASE just look at the current issues before opening your own.
Duplicate of https://github.com/shiftkey/desktop/issues/680 https://github.com/shiftkey/desktop/issues/677 https://github.com/shiftkey/desktop/issues/676 https://github.com/shiftkey/desktop/issues/674 https://github.com/shiftkey/desktop/issues/673 https://github.com/shiftkey/desktop/issues/672 https://github.com/shiftkey/desktop/issues/670 https://github.com/shiftkey/desktop/issues/669 https://github.com/shiftkey/desktop/issues/668 https://github.com/shiftkey/desktop/issues/666.

**Closed as completed** 2022-04-01 09:57 UTC
