### ISSUE TITLE
cant lunch github desktop on ubuntu 

### ISSUE THREAD

**Issue by Aswar-Group** [shiftkey/desktop#193] opened 2019-12-25 11:44 UTC
hi I install the GitHub desktop for ubuntu using this command in the terminal 

sudo snap install GitHub-desktop -- beta --classic 

it installed successfully but when trying to run the application it doesn't lunch 

so I tried to run it in the terminal to get the error message and I git this 

/snap/github-desktop/63/app/github-desktop: symbol lookup error: /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0: undefined symbol: g_date_copy

dose anyone has a solution I can do

**Comment by ilovemilk** [comment] 2019-12-25 13:16
I have the same issue. Didn't find any solution yet.

**Comment by Kenivia** [comment] 2019-12-27 06:51
I have the same issue on Ubuntu 18.04 LTS

[This forum](https://forum.snapcraft.io/t/undefined-symbol-g-date-copy-problem/12235) says that it is not something users can fix and should contact the snap authors. 

I find it very strange that such a critical issue is still not fixed after, what, 5 months now?

**Comment by yasenstar** [comment] 2019-12-28 13:29
I have same issue even I upgraded ubuntu to 20.04 development version

**Comment by immackay** [comment] 2019-12-28 19:54
Hi all, see #163 for the relevant issue. I've posted instructions for downgrading there - alternatively you can install the .deb as opposed to the snap package.

**Comment by ashwani65** [comment] 2019-12-29 12:14
I also have the same issue

**Comment by Kenivia** [comment] 2019-12-30 05:01
@immackay Many thanks! So installing using the .snap file instead of installing straight away fixed the issue. Hmmm. How weird.

**Comment by immackay** [comment] 2020-01-02 05:11
There was a packaging error with the most recent snap, causing this issue

**Comment by shiftkey** [comment] 2020-02-07 19:10
Closing this out as a duplicate of #163.

The `deb` installer is recommended until we can get to the bottom of that issue.

**Closed as completed by shiftkey** 2020-02-07 19:10 UTC
Labels: installers/snap
