### ISSUE TITLE
https://apt.packages.shiftkey.dev SSL Certificate Expired - APT Updates broken [URGENT]

### ISSUE THREAD

**Issue by Timeox2k** [shiftkey/desktop#1164] opened 2024-11-12 09:22 UTC
### The problem

Because the SSL Cert for apt.packages.shiftkey.dev got expired, apt updates via Linux Mint (& probably other Debian based Distros) are no longer working until it's removed from the Additional Sources.

### Release version

latest

### Operating system

Linux Mint

### Screenshots

![image](https://github.com/user-attachments/assets/35fc0c0d-8f5b-4c35-b12c-d7436ff033a9)
![image](https://github.com/user-attachments/assets/b01dce0b-0829-4b44-b345-f2fce1dc158c)

**Comment by nbowling** [comment] 2024-11-12 11:22
Me too...
https://apt.packages.shiftkey.dev/ubuntu any InRelease is not (yet) available (Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected.  Could not handshake: Error in the certificate verification. [IP: 2620:1ec:bdf::64 443])

**Comment by Timeox2k** [comment] 2024-11-12 12:00
Hope it gets resolved quick. I had to remove it for now.

**Comment by Timeox2k** [comment] 2024-11-12 12:00
> Me too... https://apt.packages.shiftkey.dev/ubuntu any InRelease is not (yet) available (Certificate verification failed: The certificate is NOT trusted. The name in the certificate does not match the expected. Could not handshake: Error in the certificate verification. [IP: 2620:1ec:bdf::64 443])

Hope it gets resolved quick. I had to remove it for now.

**Comment by samuel-andres** [comment] 2024-11-12 12:05
The same is happening in fedora/dnf

**Comment by Timeox2k** [comment] 2024-11-12 12:30
> The same is happening in fedora/dnf

ofc it does. An SSL Cert is global. Has nothing to do with the Distro

**Comment by shiftkey** [comment] 2024-11-12 14:45
Duplicate of #1062, please see that thread for more context

**Closed as completed by shiftkey** 2024-11-12 14:45 UTC
