### ISSUE TITLE
photo bug

### ISSUE THREAD

**Issue by TogoFire** [shiftkey/desktop#268] opened 2020-04-23 12:51 UTC
When using github desktop on ubuntu or windows my image does not appear in commits, and my photo and my name are grayed out as if I were invisible. Please fix this, this bug is annoying.

**Comment by shiftkey** [comment] 2020-04-23 12:57
@TogoFire please provide more information about the issue:

 - what version you are running
 - screenshots of the problem
 - an example repository, if possible, would greatly assist with reproducing the issue

**Comment by TogoFire** [comment] 2020-04-24 00:27
> @TogoFire please provide more information about the issue:
> 
> * what version you are running
> * screenshots of the problem
> * an example repository, if possible, would greatly assist with reproducing the issue

Screenshots:
https://prnt.sc/s4y1y0
https://prnt.sc/s4y2c0
https://prnt.sc/s4y0v6

**Comment by shiftkey** [comment] 2020-04-24 00:48
@TogoFire I had a look at the commit you created and it looks like the `user.name` and `user.email` settings are wrapped in quotes, which means it's not being associated with your GitHub account.

Here's the raw Git output:

```
$ git show HEAD
commit 8ef33ba7a6986f17fddbf47f85898dd0874349b4 (HEAD -> xtended, origin/xtended, origin/HEAD)
Author: “TogoFire” <“italomellopereira@gmail.com”>
Date:   Mon Apr 20 16:57:22 2020 -0300

    sepolicy denials untrusted and isolated

diff --git a/sepolicy/vendor/isolated_app.te b/sepolicy/vendor/isolated_app.te
...
```

This isn't something we can fix in GitHub Desktop.

**Comment by TogoFire** [comment] 2020-04-24 01:38
> @TogoFire I had a look at the commit you created and it looks like the `user.name` and `user.email` settings are wrapped in quotes, which means it's not being associated with your GitHub account.
> 
> Here's the raw Git output:
> 
> ```
> $ git show HEAD
> commit 8ef33ba7a6986f17fddbf47f85898dd0874349b4 (HEAD -> xtended, origin/xtended, origin/HEAD)
> Author: “TogoFire” <“italomellopereira@gmail.com”>
> Date:   Mon Apr 20 16:57:22 2020 -0300
> 
>     sepolicy denials untrusted and isolated
> 
> diff --git a/sepolicy/vendor/isolated_app.te b/sepolicy/vendor/isolated_app.te
> ...
> ```
> 
> This isn't something we can fix in GitHub Desktop.

Truth. It worked.
I just redone the login without quotes via the cmd terminal.

git config --global user.email youremail@gmail.com
git config --global user.name YourName

Thx!

**Comment by shiftkey** [comment] 2020-04-24 02:14
@TogoFire excellent - gonna close this out as resolved...

**Closed as completed by shiftkey** 2020-04-24 02:14 UTC
