### ISSUE TITLE
push/fetch hangs for long periods for private repository

### ISSUE THREAD

**Issue by matshou** [shiftkey/desktop#508] opened 2021-05-26 12:20 UTC
### Describe the bug

When pushing changes from local to remote using [2.8.1-linux3](https://github.com/shiftkey/desktop/releases/tag/release-2.8.1-linux3) the application hangs seemingly indefinitely.

### Version & OS

- Github Desktop 2.8.1-linux3

- Xubuntu 20.04.2

### Steps to reproduce the behavior

1. Open local repository.
2. Commit something.
3. Click on 'Push origin'.
4. Wait indefinitely...

### How to resolve the issue

- Switch from 'History' to 'Changes' tab.
- Switch focus to another application and then back to Github Desktop.
- Selecting a commit entry in 'History' tab.

**Comment by matshou** [comment] 2021-05-26 12:21
Related to issue #332

**Comment by shiftkey** [comment] 2021-05-26 12:26
@yooksi can you provide the logs from around the time this was happening? There may be some clues in there around what's happening and which Git operations are getting stuck...

**Comment by matshou** [comment] 2021-05-26 12:31
Sure, where do I look for the logs?

**Comment by shiftkey** [comment] 2021-05-26 12:57
> Attach your logs by opening the `Help` menu and selecting `Show Logs...`, if applicable.

From memory the log files are organized by day.

**Comment by matshou** [comment] 2021-05-26 13:09
This seems to be the relevant part of the log:

```
2021-05-26T13:03:33.486Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: storm - yooksi (has token)
2021-05-26T13:03:53.440Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin master:master --progress (took 19.865s)
```

Here is the full log file:
[2021-05-26.desktop.production.log](https://github.com/shiftkey/desktop/files/6546857/2021-05-26.desktop.production.log)

**Comment by matshou** [comment] 2021-05-27 09:16
The issue is also resolved by selecting a commit in 'History' tab.

**Comment by shiftkey** [comment] 2021-05-27 12:11
This feels very similar to the original issue with making commits, but perhaps is related to `stdout/stderr` of a spawned process. I haven't seen this behaviour myself, so it's early days for that investigation, but I think I need to learn what changed in Node for processes on Linux to introduce these category of issues.

Without a more obvious clue as to where/how this process is "stuck" I think a more methodical investigation is needed:

 - which version was the first to see this issue? I spot `2.5.4-linux1` in #329 so that's my leading candidate
 - if we can confirm that's the first version, and the previous version is fine, let's identify the versions of Node/Electron that changed to try and narrow down the set of changes. This can be checked in the dev tools:

<img width="552" alt="Screen Shot 2021-05-27 at 9 09 57 AM" src="https://user-images.githubusercontent.com/359239/119823543-580fc880-becb-11eb-97c4-be0a09792740.png">

 - we feel strongly that this is related to `child_process` changes in Node, so searching for interesting issues like https://github.com/nodejs/node/issues/20503 once we know the exact version or commits involved that we may need to handle better in the app.

**Comment by krushnaj** [comment] 2021-05-28 10:21
@shiftkey Yes the pull and push processes started getting stuck from `2.5.4-linux1`. I can confirm this as I use the `2.5.3-linux1` on my laptop.

**Comment by tImIbreakdown** [comment] 2021-06-07 14:28
Push/Pull in version 2.8.3 Linux RC1 works for me without changing focus, switching tabs, etc.

**Comment by masseelch** [comment] 2021-06-07 14:44
@shiftkey This seems to only happen when the origin is set via https (which github desktop uses on cloning repos from github). I have some "old" repos I cloned via git cli.On that repos the push does happen smooth and fast.

I manually changed the remote url to use ssh instead of https and the issue went away.

**Comment by jordan4ibanez** [comment] 2021-06-30 23:50
I can confirm this, still happening with 2.9.0 rc2, on fedora 34 - I usually make this work by clicking off the window to another then clicking back to it and it pushes finally

**Comment by orrinoAriel** [comment] 2021-07-01 22:54
This issue is still happening in version 2.9.0 rc2...the same problem and solution of the user that comment before than me @jordan4ibanez...in my case, this issue is happening in fetch and push...in logs I could see this(when I tried to do a fetch) :

2021-07-01T19:19:38.605Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 8.618s)
2021-07-01T22:47:14.007Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 1424.926s)
2021-07-01T22:47:16.684Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 16 repositories took 3.9s of which 0.0s paused, total 3.9s
2021-07-01T22:47:19.423Z - info: [ui] [BranchPruner] No branches to prune.
2021-07-01T22:47:31.628Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 12.388s)
2021-07-01T22:47:33.925Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: MY-REPO - MY-USER (has token)
2021-07-01T22:47:42.259Z - info: [ui] Executing pull: git -c credential.helper= -c protocol.version=2 -c rebase.backend=merge pull --progress origin (took 8.270s)
2021-07-01T22:47:44.923Z - info: [main] opening in browser: https://github.com/shiftkey/desktop/releases/
2021-07-01T23:03:47.955Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 323.160s)

**Comment by aniaptebsft** [comment] 2021-07-06 18:18
I can confirm that this issue is happening in Version 2.9.0-linux2 (x64). I am running it on Pop!_OS 21.04 (ubuntu)
To workaround, i need to remove focus and give back focus to the github desktop window either by clicking on another app and then coming back to this. Or, by clicking on changes and then history repeatedly.
This hang issue happens everytime the app contacts github server for pull, push.
For example, during the hang, I see that the status is stuck on "Fetching/Pull origin" and then when i make the window lose focus and then gain focus, it completes the pull immediately.

**Comment by shiftkey** [comment] 2021-07-06 19:39
@orrinoAriel @aniaptebsft thanks for digging into this a bit. I'm curious about the repositories that are causing you issues - are they private repositories (where authentication is needed for push and fetch) or public repositories (where authentication is needed for push only)?

Trying to nail down a good repro of this myself and I haven't investigated that area yet (there's a `desktop-trampoline` helper that's new which might yield answers here).

**Comment by aniaptebsft** [comment] 2021-07-06 19:57
I'm using all private repos.

**Comment by orrinoAriel** [comment] 2021-07-06 19:59
@shiftkey , thanks to you!! 
I'm using all private repositories too.

**Comment by shiftkey** [comment] 2021-07-06 20:02
@aniaptebsft @orrinoAriel ok cool, that's a very helpful clue! I'll do some investigating and report back if I have any other questions you could help with..

**Comment by orrinoAriel** [comment] 2021-07-21 02:43
@shiftkey Hi! how are you? Do you have any news about this?

**Comment by shiftkey** [comment] 2021-07-22 11:48
> @shiftkey Hi! how are you? Do you have any news about this?

No change recently, too busy with other things. Much like the original fix https://github.com/shiftkey/dugite/pull/1 I don't really understand _why_ this is happening, and why the fix works for this, because I haven't had time to sit down and do some focused investigation.

My working theory is that the upstream Desktop has changed some part of the authentication flow - using this new https://github.com/desktop/askpass-trampoline Node module maybe? - and something in there needs to change.

**Comment by hholst80** [comment] 2021-07-27 10:12
Similar behavior on my side. Was slow in 2.6.x and slow in 2.9.0

> 2021-07-27T10:06:50.122Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin remove-non-multioutput-code-path:remove-non-multioutput-code-path --force-with-lease --progress ***(took 262.313s)***

```
2021-07-27T09:44:49.057Z - info: [ui] [AppStore] loading 4 repositories from store
2021-07-27T09:44:49.059Z - info: [ui] [AppStore] found account: hholst80 (Henrik Holst)
2021-07-27T09:44:49.445Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:44:49.617Z - info: [ui] launching: 2.9.0-linux4 (Linux 5.4.0-77-generic)
2021-07-27T09:44:49.617Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
2021-07-27T09:44:49.647Z - info: [ui] [BranchPruner] Pruning 0 branches that have been merged into the default branch, master (c1487dd59d93158cc09e954109c6a91cc8f08459), from '

2021-07-27T09:44:49.721Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:45:05.771Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 6.064s)
2021-07-27T09:45:05.903Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:45:13.236Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: vendor - hholst80 (has token)
2021-07-27T09:45:31.423Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:45:32.154Z - info: [ui] Executing pull: git -c credential.helper= -c protocol.version=2 -c rebase.backend=merge pull --progress origin (took 18.873s)
2021-07-27T09:45:32.295Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:46:07.070Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: vendor - hholst80 (has token)
2021-07-27T09:46:07.208Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:46:50.602Z - error: [ui] Highlighter worked failed for new contents
Error: timed out
    at /home/om/webpack:/app/src/lib/highlighter/worker.ts:85:14
2021-07-27T09:47:11.731Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:47:12.782Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 3 repositories took 0.9s of which 0.2s paused, total 1.2s
2021-07-27T09:47:12.854Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:47:19.861Z - info: [ui] [AppStore] loading 4 repositories from store
2021-07-27T09:47:19.863Z - info: [ui] [AppStore] found account: hholst80 (Henrik Holst)
2021-07-27T09:47:20.170Z - info: [ui] [BranchPruner] Last prune took place in a day - skipping
2021-07-27T09:47:20.272Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:47:20.510Z - info: [ui] launching: 2.9.0-linux4 (Linux 5.4.0-77-generic)
2021-07-27T09:47:20.511Z - info: [ui] execPath: '/usr/lib/github-desktop/github-desktop'
2021-07-27T09:49:59.345Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:50:00.308Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 3 repositories took 1.1s of which 0.0s paused, total 1.1s
2021-07-27T09:51:12.868Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:51:33.447Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:52:19.352Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:52:35.769Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:52:53.267Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:53:18.153Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:55:37.434Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:55:58.074Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:56:39.557Z - info: [ui] [Timing] Action 'create commit' for 'acme/vendor' took 0.001s
2021-07-27T09:56:45.517Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:56:45.862Z - info: [ui] [squash] starting rebase for remove-non-multioutput-code-path at 71f7f2faf0281d767405361dd0b10686408bc863
2021-07-27T09:56:45.862Z - info: [ui] [squash] to restore the previous state if this completed rebase is unsatisfactory:
2021-07-27T09:56:45.862Z - info: [ui] [squash] - git checkout remove-non-multioutput-code-path
2021-07-27T09:56:45.862Z - info: [ui] [squash] - git reset 71f7f2faf0281d767405361dd0b10686408bc863 --hard
2021-07-27T09:56:46.032Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:57:10.328Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: vendor - hholst80 (has token)
2021-07-27T09:57:38.057Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin remove-non-multioutput-code-path:remove-non-multioutput-code-path --force-with-lease --progress (took 27.661s)
2021-07-27T09:58:58.544Z - info: [ui] Executing fetch: git -c credential.helper= -c protocol.version=2 fetch --progress --prune origin (took 80.440s)
2021-07-27T09:58:59.028Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T09:59:41.261Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T10:01:29.658Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T10:01:45.167Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T10:01:45.367Z - info: [ui] [Timing] Action 'create commit' for 'acme/vendor' took 0.398s
2021-07-27T10:02:05.281Z - info: [ui] [Timing] Action 'create commit' for 'acme/vendor' took 0.019s
2021-07-27T10:02:05.495Z - info: [ui] [squash] starting rebase for remove-non-multioutput-code-path at ec425d346b707e1b638af5a77400ddc57c35a4b1
2021-07-27T10:02:05.496Z - info: [ui] [squash] to restore the previous state if this completed rebase is unsatisfactory:
2021-07-27T10:02:05.496Z - info: [ui] [squash] - git checkout remove-non-multioutput-code-path
2021-07-27T10:02:05.496Z - info: [ui] [squash] - git reset ec425d346b707e1b638af5a77400ddc57c35a4b1 --hard
2021-07-27T10:02:05.647Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T10:02:27.749Z - info: [ui] [AppStore.withAuthenticatingUser] account found for repository: vendor - hholst80 (has token)
2021-07-27T10:05:04.678Z - info: [ui] [RepositoryIndicatorUpdater]: Refreshing sidebar indicators for 3 repositories took 1.1s of which 0.0s paused, total 1.1s
2021-07-27T10:06:47.531Z - warn: [ui] Unexpected value found for pull.rebase in config: 'merges'
2021-07-27T10:06:50.122Z - info: [ui] Executing push: git -c credential.helper= -c protocol.version=2 push origin remove-non-multioutput-code-path:remove-non-multioutput-code-path --force-with-lease --progress (took 262.313s)

```

**Comment by mimbrero** [comment] 2021-07-27 13:59
App hanging when committing or discarding changes was fixed, but this new bug is also happening to me (and my friend) when before it wasn't 😢

**Comment by CantStopMyBrain** [comment] 2021-08-13 16:37
Late replies to post on just-closed #573:
@shiftkey: yes, this is occuring for private repositories;
@hholst80: no, I'm not using VS Code

**Comment by Raymo111** [comment] 2021-08-27 04:34
I'm getting this issue with all repos, including public ones. Using Arch (`5.13.12-arch1-1`) and version `2.9.0` of GH desktop.

**Comment by TowelSniffer** [comment] 2021-08-27 23:05
2.9.2 seemed to fix this issue for me on Manjaro

**Comment by Raymo111** [comment] 2021-08-28 00:50
Can confirm that too, thanks folks!

**Comment by shiftkey** [comment] 2021-08-29 15:36
> 2.9.2 seemed to fix this issue for me on Manjaro

This is great to hear, as I wasn't quite sure where to dig into this exactly. I did upgrade the version of Electron in this release via e778d1be3a08123fcf2f8dcc84eaf005200424f3 which may have been a factor. Going to leave this open and see if others are satisfied with the latest release...

**Comment by orrinoAriel** [comment] 2021-08-30 18:59
Works fine now on Mint!! I'm thrilled!! :1st_place_medal:

**Comment by aniaptebsft** [comment] 2021-08-31 07:28
I upgraded from 2.9.0 to 2.9.2 and this works fine now. No hangs. I'm on PopOs 21.04 latest.

**Comment by borodinalive** [comment] 2021-08-31 08:55
Hi, everyone
I have the same issue with fetching/pulling via vpn connection, repository address with https. 2.9.0. and 2.9.2 works the same. ​I used to be complain on hangups which solved by focus out from the app and focus in back. I assume that this issue may have the same source. Maybe some preferences on remote host. 26/08 all works like always (with focus out/in) but from 30/08 something changed and I can't even fetch remote branch

When I work with my public github repository all works fine. No hangups.

UPDATE: There is no such problem on Fedora 34. All is fine

**Comment by CantStopMyBrain** [comment] 2021-09-07 09:25
Upgrading to 2.9.2 resolved the problems, including when working with private repos, on Ubuntu 20.04. Thanks!

**Comment by krushnaj** [comment] 2021-09-07 09:38
@shiftkey `v2.9.3` works well with private repository on Ubuntu 21.04.

**Comment by mimbrero** [comment] 2021-09-09 10:19
Everybody happy with 2.9.2, this issue can be closed now 👍🏿

**Comment by ShanePark** [comment] 2021-09-27 05:53
my 2.8.0  had same issue before, after upgrading to 2.9.3 It perfectly works. many thanks

**Comment by shiftkey** [comment] 2021-09-30 19:44
Closing this out as I've not heard anyone still seeing this issue 🎉

**Closed as completed by shiftkey** 2021-09-30 19:44 UTC
Labels: needs-investigation
