### ISSUE TITLE
Github desktop remote url not updated into new one

### ISSUE THREAD

**Issue by cethol** [shiftkey/desktop#371] opened 2020-11-09 01:56 UTC
### Describe the bug

Hi, i have transfer the ownership of the repository into organization, everything works fine untill i open github desktop and it says 
![image](https://user-images.githubusercontent.com/2105802/98491794-8a781200-2268-11eb-99ad-5dcb1b44cff4.png)
I am using command line working well, but from github desktop, i still got this error. I have change the remote url in the configuration, like this. 
![image](https://user-images.githubusercontent.com/2105802/98491843-ae3b5800-2268-11eb-83a6-f20b228be07d.png)

the old repository is from `https://github.com/cethol/logisly.git`

### Version & OS

![image](https://user-images.githubusercontent.com/2105802/98491877-c612dc00-2268-11eb-915b-4de9869d0ce4.png)
I am using Elementary OS which based on Ubuntu dist.

### Steps to reproduce the behavior

1. Open existing repository in Github Desktop
2. Transfer ownership of the repository to another account/organization
3. Change the repository configuration in Github Desktop
4. See Error

### Expected behavior

Should be fine, because when i am using command line it's working well.

### Actual behavior

![image](https://user-images.githubusercontent.com/2105802/98491987-1d18b100-2269-11eb-9b2a-932ef9eb9c72.png)

### Screenshots

![image](https://user-images.githubusercontent.com/2105802/98492000-2275fb80-2269-11eb-9565-e520a65bb9d4.png)

**Comment by cethol** [comment] 2020-11-26 10:23
Hi i have new update information about this issue.
So, the issue is in the authorization oauth apps. Before the repository transferred into new github team, i already grant the github desktop for my github, this is not updated with the organization even if i am logout and login again, it need to be revoked from the github settings (check the image)  then grant access to the organization. But in windows, this issue is not happen, so i think this happen only in this linux version only. Thanks.

![image](https://user-images.githubusercontent.com/2105802/100339063-f51ca200-300b-11eb-920a-79773657ea2a.png)

**Comment by shiftkey** [comment] 2020-12-17 19:33
@cethol thanks for the follow up!

>  But in windows, this issue is not happen, so i think this happen only in this linux version only

The root cause of this is ultimately #228 and given we can't address this specific issue I'm going to close this out.

**Closed as completed by shiftkey** 2020-12-17 19:33 UTC
